<?php

use App\University;
use Illuminate\Database\Seeder;

class TaiwanUniversitySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $highschools = [
            ['english_name'=>'Taipei Municipal Da Tong High School, Taipei', 'chinese_name'=>'台北市立大同高級中學', 'area' => 'HIGHSCHOOL', 'country'=>'TAIWAN', 'school_badge'=>'TWH1', 'image_path' => 'university/TAIWAN/TWH1.png'],
            ['english_name'=>'Tam Kang Senior High School', 'chinese_name'=>'新北市私立淡江高級中學', 'area' => 'HIGHSCHOOL', 'country'=>'TAIWAN', 'school_badge'=>'TWH2', 'image_path' => 'university/TAIWAN/TWH2.png'],
            ['english_name'=>'Kuang Jen Catholic High School', 'chinese_name'=>'新北市光仁高級中學', 'area' => 'HIGHSCHOOL', 'country'=>'TAIWAN', 'school_badge'=>'TWH3', 'image_path' => 'university/TAIWAN/TWH3.png'],
            ['english_name'=>'Taipei Municipal Cheng Kung Senior High School, Taipei', 'chinese_name'=>'台北市立成功高級中學', 'area' => 'HIGHSCHOOL', 'country'=>'TAIWAN', 'school_badge'=>'TWH4', 'image_path' => 'university/TAIWAN/TWH4.png'],
            ['english_name'=>'Banqiao Senior High School, New Taipei City', 'chinese_name'=>'新北市立板橋高級中學', 'area' => 'HIGHSCHOOL', 'country'=>'TAIWAN', 'school_badge'=>'TWH5', 'image_path' => 'university/TAIWAN/TWH5.png'],
            ['english_name'=>'Bei Da High School, New Taipei City', 'chinese_name'=>'新北市立北大高中', 'area' => 'HIGHSCHOOL', 'country'=>'TAIWAN', 'school_badge'=>'TWH6', 'image_path' => 'university/TAIWAN/TWH6.png'],
            ['english_name'=>'Guangfu Senior High School, Hsinchu City', 'chinese_name'=>'新竹市立光復高級中學', 'area' => 'HIGHSCHOOL', 'country'=>'TAIWAN', 'school_badge'=>'TWH7', 'image_path' => 'university/TAIWAN/TWH7.png'],
            ['english_name'=>'National Taichung First Senior High School, Taichung', 'chinese_name'=>'台中市立臺中一中', 'area' => 'HIGHSCHOOL', 'country'=>'TAIWAN', 'school_badge'=>'TWH8', 'image_path' => 'university/TAIWAN/TWH8.png'],
            ['english_name'=>'Feng Yuan Senior High School, Taichung', 'chinese_name'=>'台中市立豐原高級中學', 'area' => 'HIGHSCHOOL', 'country'=>'TAIWAN', 'school_badge'=>'TWH9', 'image_path' => 'university/TAIWAN/TWH9.png'],
            ['english_name'=>'Nan Kuang Senior High School, Tainan', 'chinese_name'=>'台南市立南光高級中學', 'area' => 'HIGHSCHOOL', 'country'=>'TAIWAN', 'school_badge'=>'TWH10', 'image_path' => 'university/TAIWAN/TWH10.png'],
            ['english_name'=>'Taipei Municipal Da An Vocational High School', 'chinese_name'=>'臺北市立大安高級工業職業學校', 'area' => 'HIGHSCHOOL', 'country'=>'TAIWAN', 'school_badge'=>'TWH11', 'image_path' => 'university/TAIWAN/TWH11.png'],
            ['english_name'=>'Affiliated Senior High School of National Taiwan Normal University', 'chinese_name'=>'國立台灣師範大學附屬高級中學', 'area' => 'HIGHSCHOOL', 'country'=>'TAIWAN', 'school_badge'=>'TWH12', 'image_path' => 'university/TAIWAN/TWH12.png'],
            ['english_name'=>'Affiliated Senior High School of National Kaohsiung Normal University', 'chinese_name'=>'國立高雄師範大學附屬高級中學', 'area' => 'HIGHSCHOOL', 'country'=>'TAIWAN', 'school_badge'=>'TWH13', 'image_path' => 'university/TAIWAN/TWH13.png'],
            ['english_name'=>'Taipei Municipal Jing Mei Girls High School', 'chinese_name'=>'景美女子高級中學', 'area' => 'HIGHSCHOOL', 'country'=>'TAIWAN', 'school_badge'=>'TWH14', 'image_path' => 'university/TAIWAN/TWH14.png'],
            ['english_name'=>'Kao Hsiung Senior High School', 'chinese_name'=>'高雄市立高雄高級中學', 'area' => 'HIGHSCHOOL', 'country'=>'TAIWAN', 'school_badge'=>'TWH15', 'image_path' => 'university/TAIWAN/TWH15.png'],
            ['english_name'=>'Xin Dian Senior High School', 'chinese_name'=>'新北市立新店高級中學', 'area' => 'HIGHSCHOOL', 'country'=>'TAIWAN', 'school_badge'=>'TWH16', 'image_path' => 'university/TAIWAN/TWH16.png'],
            ['english_name'=>'Nan Ke International Experimental High School', 'chinese_name'=>'台南市立南科國際實驗高級中學', 'area' => 'HIGHSCHOOL', 'country'=>'TAIWAN', 'school_badge'=>'TWH17', 'image_path' => 'university/TAIWAN/TWH17.png'],
            ['english_name'=>'Hsin Chu Senior High School', 'chinese_name'=>'新竹市立新竹高級中學', 'area' => 'HIGHSCHOOL', 'country'=>'TAIWAN', 'school_badge'=>'TWH18', 'image_path' => 'university/TAIWAN/TWH18.png'],
            ['english_name'=>'Taipei Municipal Xi Song High School', 'chinese_name'=>'台北市西松高級中學', 'area' => 'HIGHSCHOOL', 'country'=>'TAIWAN', 'school_badge'=>'TWH19', 'image_path' => 'university/TAIWAN/TWH19.png'],
            ['english_name'=>'Taipei Municipal Zhong Zheng Senior High School', 'chinese_name'=>'臺北市立中正高級中學', 'area' => 'HIGHSCHOOL', 'country'=>'TAIWAN', 'school_badge'=>'TWH20', 'image_path' => 'university/TAIWAN/TWH20.png'],
            ['english_name'=>'Taipei Municipal Jian Guo High School', 'chinese_name'=>'臺北市立建國高級中學', 'area' => 'HIGHSCHOOL', 'country'=>'TAIWAN', 'school_badge'=>'TWH21', 'image_path' => 'university/TAIWAN/TWH21.png'],
            ['english_name'=>'Taipei Municipal Taipei First Girls High School', 'chinese_name'=>'臺北市立第一女子高級中學', 'area' => 'HIGHSCHOOL', 'country'=>'TAIWAN', 'school_badge'=>'TWH22', 'image_path' => 'university/TAIWAN/TWH22.png'],
            ['english_name'=>'Taipei Municipal Da Zhi High School', 'chinese_name'=>'臺北市大直高級中學', 'area' => 'HIGHSCHOOL', 'country'=>'TAIWAN', 'school_badge'=>'TWH23', 'image_path' => 'university/TAIWAN/TWH23.png'],
            ['english_name'=>'Blessed Imelda Girls High School', 'chinese_name'=>'臺北市私立靜修高級中學', 'area' => 'HIGHSCHOOL', 'country'=>'TAIWAN', 'school_badge'=>'TWH24', 'image_path' => 'university/TAIWAN/TWH24.png'],
            ['english_name'=>'Taipei Municipal Zhong Shan Girls High School', 'chinese_name'=>'臺北市立中山女子高級中學', 'area' => 'HIGHSCHOOL', 'country'=>'TAIWAN', 'school_badge'=>'TWH25', 'image_path' => 'university/TAIWAN/TWH25.png'],
            ['english_name'=>'Dao Jiang High School of Nursing and Home Economics', 'chinese_name'=>'臺北市私立稻江高級護理家事職業學校', 'area' => 'HIGHSCHOOL', 'country'=>'TAIWAN', 'school_badge'=>'TWH26', 'image_path' => 'university/TAIWAN/TWH26.png'],
            ['english_name'=>'Taipei Municipal Zhong Lun High School', 'chinese_name'=>'臺北市立中崙高級中學', 'area' => 'HIGHSCHOOL', 'country'=>'TAIWAN', 'school_badge'=>'TWH27', 'image_path' => 'university/TAIWAN/TWH27.png'],
            ['english_name'=>'Yu Da High School of Commerce and Home Economics', 'chinese_name'=>'臺北市私立育達高級中等學校', 'area' => 'HIGHSCHOOL', 'country'=>'TAIWAN', 'school_badge'=>'TWH28', 'image_path' => 'university/TAIWAN/TWH28.png'],
            ['english_name'=>'Taipei Municipal He Ping High School', 'chinese_name'=>'臺北市立和平高級中學', 'area' => 'HIGHSCHOOL', 'country'=>'TAIWAN', 'school_badge'=>'TWH29', 'image_path' => 'university/TAIWAN/TWH29.png'],
            ['english_name'=>'Taipei Municipal Wan Fang Senior High School', 'chinese_name'=>'臺北市立萬芳高級中學', 'area' => 'HIGHSCHOOL', 'country'=>'TAIWAN', 'school_badge'=>'TWH30', 'image_path' => 'university/TAIWAN/TWH30.png'],
            ['english_name'=>'Yan Ping High School', 'chinese_name'=>'臺北市私立延平高級中學', 'area' => 'HIGHSCHOOL', 'country'=>'TAIWAN', 'school_badge'=>'TWH31', 'image_path' => 'university/TAIWAN/TWH31.png'],
            ['english_name'=>'Jinou Girls High School', 'chinese_name'=>'臺北市私立金甌女子高級中學', 'area' => 'HIGHSCHOOL', 'country'=>'TAIWAN', 'school_badge'=>'TWH32', 'image_path' => 'university/TAIWAN/TWH32.png'],
            ['english_name'=>'Taipei Municipal Song Shan High School', 'chinese_name'=>'臺北市立松山高級中學', 'area' => 'HIGHSCHOOL', 'country'=>'TAIWAN', 'school_badge'=>'TWH33', 'image_path' => 'university/TAIWAN/TWH33.png'],
            ['english_name'=>'Taipei Municipal Yong Chun High School', 'chinese_name'=>'臺北市立永春高級中學', 'area' => 'HIGHSCHOOL', 'country'=>'TAIWAN', 'school_badge'=>'TWH34', 'image_path' => 'university/TAIWAN/TWH34.png'],
            ['english_name'=>'Taipei Municipal Yang Ming High School', 'chinese_name'=>'臺北市立陽明高級中學', 'area' => 'HIGHSCHOOL', 'country'=>'TAIWAN', 'school_badge'=>'TWH35', 'image_path' => 'university/TAIWAN/TWH35.png'],
            ['english_name'=>'Taipei Municipal Bai Ling High School', 'chinese_name'=>'臺北市立百齡高級中學', 'area' => 'HIGHSCHOOL', 'country'=>'TAIWAN', 'school_badge'=>'TWH36', 'image_path' => 'university/TAIWAN/TWH36.png'],
            ['english_name'=>'Wesley Girls High School', 'chinese_name'=>'臺北市私立衛理女子高級中學', 'area' => 'HIGHSCHOOL', 'country'=>'TAIWAN', 'school_badge'=>'TWH37', 'image_path' => 'university/TAIWAN/TWH37.png'],
            ['english_name'=>'Hua Xing High School', 'chinese_name'=>'臺北市私立華興高級中學', 'area' => 'HIGHSCHOOL', 'country'=>'TAIWAN', 'school_badge'=>'TWH38', 'image_path' => 'university/TAIWAN/TWH38.png'],
            ['english_name'=>'Hua Gang High School of Arts', 'chinese_name'=>'臺北市私立華岡藝術學校', 'area' => 'HIGHSCHOOL', 'country'=>'TAIWAN', 'school_badge'=>'TWH39', 'image_path' => 'university/TAIWAN/TWH39.png'],
            ['english_name'=>'Taipei Municipal Nei Hu High School', 'chinese_name'=>'臺北市立內湖高級中學', 'area' => 'HIGHSCHOOL', 'country'=>'TAIWAN', 'school_badge'=>'TWH40', 'image_path' => 'university/TAIWAN/TWH40.png'],
            ['english_name'=>'Taipei Municipal Li Shan High School', 'chinese_name'=>'臺北市立麗山高級中學', 'area' => 'HIGHSCHOOL', 'country'=>'TAIWAN', 'school_badge'=>'TWH41', 'image_path' => 'university/TAIWAN/TWH41.png'],
            ['english_name'=>'Taipei Municipal Nan Hu High School', 'chinese_name'=>'臺北市立南湖高級中學', 'area' => 'HIGHSCHOOL', 'country'=>'TAIWAN', 'school_badge'=>'TWH42', 'image_path' => 'university/TAIWAN/TWH42.png'],
            ['english_name'=>'Da Ren Girls High School', 'chinese_name'=>'臺北市私立達人女子高級中學', 'area' => 'HIGHSCHOOL', 'country'=>'TAIWAN', 'school_badge'=>'TWH43', 'image_path' => 'university/TAIWAN/TWH43.png'],
            ['english_name'=>'Taipei Municipal Nan Gang High School', 'chinese_name'=>'臺北市立南港高級中學', 'area' => 'HIGHSCHOOL', 'country'=>'TAIWAN', 'school_badge'=>'TWH44', 'image_path' => 'university/TAIWAN/TWH44.png'],
            ['english_name'=>'Taipei Municipal Yu Cheng High School', 'chinese_name'=>'臺北市立育成高級中學', 'area' => 'HIGHSCHOOL', 'country'=>'TAIWAN', 'school_badge'=>'TWH45', 'image_path' => 'university/TAIWAN/TWH45.png'],
            ['english_name'=>'The Affiliated High School of National Chengchi University', 'chinese_name'=>'國立政治大學附屬高級中學', 'area' => 'HIGHSCHOOL', 'country'=>'TAIWAN', 'school_badge'=>'TWH46', 'image_path' => 'university/TAIWAN/TWH46.png'],
            ['english_name'=>'Dong Shan High School', 'chinese_name'=>'臺北市私立東山高級中學', 'area' => 'HIGHSCHOOL', 'country'=>'TAIWAN', 'school_badge'=>'TWH47', 'image_path' => 'university/TAIWAN/TWH47.png'],
            ['english_name'=>'Tsai Hsing High School', 'chinese_name'=>'臺北市私立再興高級中學', 'area' => 'HIGHSCHOOL', 'country'=>'TAIWAN', 'school_badge'=>'TWH48', 'image_path' => 'university/TAIWAN/TWH48.png'],
            ['english_name'=>'Ching Shin Academy', 'chinese_name'=>'臺北市私立靜心高級中學', 'area' => 'HIGHSCHOOL', 'country'=>'TAIWAN', 'school_badge'=>'TWH49', 'image_path' => 'university/TAIWAN/TWH49.png'],
            ['english_name'=>'Hujiang High School', 'chinese_name'=>'臺北市私立滬江高級中學', 'area' => 'HIGHSCHOOL', 'country'=>'TAIWAN', 'school_badge'=>'TWH50', 'image_path' => 'university/TAIWAN/TWH50.png'],
            ['english_name'=>'Ta Tung High School', 'chinese_name'=>'臺北市私立大同高級中學', 'area' => 'HIGHSCHOOL', 'country'=>'TAIWAN', 'school_badge'=>'TWH51', 'image_path' => 'university/TAIWAN/TWH51.png'],
            ['english_name'=>'Ta Nai Senior High School', 'chinese_name'=>'台南第一高級中學', 'area' => 'HIGHSCHOOL', 'country'=>'TAIWAN', 'school_badge'=>'TWH52', 'image_path' => 'university/TAIWAN/TWH52.png'],
            ['english_name'=>'Ta Nai Girls Senior High School', 'chinese_name'=>'台南女子高級中學', 'area' => 'HIGHSCHOOL', 'country'=>'TAIWAN', 'school_badge'=>'TWH53', 'image_path' => 'university/TAIWAN/TWH53.png'],
            ['english_name'=>'Chang Jung Senior High School', 'chinese_name'=>'長榮高級中學', 'area' => 'HIGHSCHOOL', 'country'=>'TAIWAN', 'school_badge'=>'TWH54', 'image_path' => 'university/TAIWAN/TWH54.png'],
            ['english_name'=>'Chang Jung Girls High School', 'chinese_name'=>'長榮女子高級中學', 'area' => 'HIGHSCHOOL', 'country'=>'TAIWAN', 'school_badge'=>'TWH55', 'image_path' => 'university/TAIWAN/TWH55.png'],
            ['english_name'=>'Kaohsiung Municipal Kaohsiung Girls Senior High School', 'chinese_name'=>'高雄市立高雄女子高級中學', 'area' => 'HIGHSCHOOL', 'country'=>'TAIWAN', 'school_badge'=>'TWH56', 'image_path' => 'university/TAIWAN/TWH56.png'],
        ];

        $university = [
            ['english_name'=>'National Taiwan University', 'chinese_name'=>'國立臺灣大學', 'area' => 'COLLEGE', 'country'=>'TAIWAN', 'school_badge'=>'TW1', 'image_path' => 'university/TAIWAN/TW1.png'],
            ['english_name'=>'National Chung Hsing University', 'chinese_name'=>'國立中興大學', 'area' => 'COLLEGE', 'country'=>'TAIWAN', 'school_badge'=>'TW2', 'image_path' => 'university/TAIWAN/TW2.png'],
            ['english_name'=>'National Taiwan Normal University', 'chinese_name'=>'國立臺灣師範大學', 'area' => 'COLLEGE', 'country'=>'TAIWAN', 'school_badge'=>'TW3', 'image_path' => 'university/TAIWAN/TW3.png'],
            ['english_name'=>'National Cheng Kung UniversityTW', 'chinese_name'=>'國立成功大學', 'area' => 'COLLEGE', 'country'=>'TAIWAN', 'school_badge'=>'TW4', 'image_path' => 'university/TAIWAN/TW4.png'],
            ['english_name'=>'National Chengchi University', 'chinese_name'=>'國立政治大學', 'area' => 'COLLEGE', 'country'=>'TAIWAN', 'school_badge'=>'TW5', 'image_path' => 'university/TAIWAN/TW5.png'],
            ['english_name'=>'National Taipei University', 'chinese_name'=>'國立臺北大學', 'area' => 'COLLEGE', 'country'=>'TAIWAN', 'school_badge'=>'TW6', 'image_path' => 'university/TAIWAN/TW6.png'],
            ['english_name'=>'National Tsing Hua University', 'chinese_name'=>'國立清華大學', 'area' => 'COLLEGE', 'country'=>'TAIWAN', 'school_badge'=>'TW7', 'image_path' => 'university/TAIWAN/TW7.png'],
            ['english_name'=>'National Central University', 'chinese_name'=>'國立中央大學', 'area' => 'COLLEGE', 'country'=>'TAIWAN', 'school_badge'=>'TW8', 'image_path' => 'university/TAIWAN/TW8.png'],
            ['english_name'=>'National Taiwan Ocean University', 'chinese_name'=>'國立臺灣海洋大學', 'area' => 'COLLEGE', 'country'=>'TAIWAN', 'school_badge'=>'TW9', 'image_path' => 'university/TAIWAN/TW9.png'],
            ['english_name'=>'National Kaohsiung Normal University', 'chinese_name'=>'國立高雄師範大學', 'area' => 'COLLEGE', 'country'=>'TAIWAN', 'school_badge'=>'TW10', 'image_path' => 'university/TAIWAN/TW10.png'],
            ['english_name'=>'National Changhua University of Education', 'chinese_name'=>'國立彰化師範大學', 'area' => 'COLLEGE', 'country'=>'TAIWAN', 'school_badge'=>'TW11', 'image_path' => 'university/TAIWAN/TW11.png'],
            ['english_name'=>'National Sun Yat-sen University', 'chinese_name'=>'國立中山大學', 'area' => 'COLLEGE', 'country'=>'TAIWAN', 'school_badge'=>'TW12', 'image_path' => 'university/TAIWAN/TW12.png'],
            ['english_name'=>'National Chung Cheng University', 'chinese_name'=>'國立中正大學', 'area' => 'COLLEGE', 'country'=>'TAIWAN', 'school_badge'=>'TW13', 'image_path' => 'university/TAIWAN/TW13.png'],
            ['english_name'=>'National Ilan University', 'chinese_name'=>'國立宜蘭大學', 'area' => 'COLLEGE', 'country'=>'TAIWAN', 'school_badge'=>'TW14', 'image_path' => 'university/TAIWAN/TW14.png'],
            ['english_name'=>'National Taipei University of Education', 'chinese_name'=>'國立臺北教育大學', 'area' => 'COLLEGE', 'country'=>'TAIWAN', 'school_badge'=>'TW15', 'image_path' => 'university/TAIWAN/TW15.png'],
            ['english_name'=>'Taipei National University of the Arts', 'chinese_name'=>'國立臺北藝術大學', 'area' => 'COLLEGE', 'country'=>'TAIWAN', 'school_badge'=>'TW16', 'image_path' => 'university/TAIWAN/TW16.png'],
            ['english_name'=>'National Taitung University', 'chinese_name'=>'國立臺東大學', 'area' => 'COLLEGE', 'country'=>'TAIWAN', 'school_badge'=>'TW17', 'image_path' => 'university/TAIWAN/TW17.png'],
            ['english_name'=>'National Taiwan Sport University', 'chinese_name'=>'國立體育大學', 'area' => 'COLLEGE', 'country'=>'TAIWAN', 'school_badge'=>'TW18', 'image_path' => 'university/TAIWAN/TW18.png'],
            ['english_name'=>'National University of Tainan', 'chinese_name'=>'國立臺南大學', 'area' => 'COLLEGE', 'country'=>'TAIWAN', 'school_badge'=>'TW19', 'image_path' => 'university/TAIWAN/TW19.png'],
            ['english_name'=>'National Taichung University of Education', 'chinese_name'=>'國立臺中教育大學', 'area' => 'COLLEGE', 'country'=>'TAIWAN', 'school_badge'=>'TW20', 'image_path' => 'university/TAIWAN/TW20.png'],
            ['english_name'=>'National Taiwan University of Arts', 'chinese_name'=>'國立臺灣藝術大學', 'area' => 'COLLEGE', 'country'=>'TAIWAN', 'school_badge'=>'TW21', 'image_path' => 'university/TAIWAN/TW21.png'],
            ['english_name'=>'National Dong Hwa University', 'chinese_name'=>'國立東華大學', 'area' => 'COLLEGE', 'country'=>'TAIWAN', 'school_badge'=>'TW22', 'image_path' => 'university/TAIWAN/TW22.png'],
            ['english_name'=>'National Chi Nan University', 'chinese_name'=>'國立暨南國際大學', 'area' => 'COLLEGE', 'country'=>'TAIWAN', 'school_badge'=>'TW23', 'image_path' => 'university/TAIWAN/TW23.png'],
            ['english_name'=>'National Taiwan University of Sport', 'chinese_name'=>'國立臺灣體育運動大學', 'area' => 'COLLEGE', 'country'=>'TAIWAN', 'school_badge'=>'TW24', 'image_path' => 'university/TAIWAN/TW24.png'],
            ['english_name'=>'Tainan National University of the Arts', 'chinese_name'=>'國立臺南藝術大學', 'area' => 'COLLEGE', 'country'=>'TAIWAN', 'school_badge'=>'TW25', 'image_path' => 'university/TAIWAN/TW25.png'],
            ['english_name'=>'National United University', 'chinese_name'=>'國立聯合大學', 'area' => 'COLLEGE', 'country'=>'TAIWAN', 'school_badge'=>'TW26', 'image_path' => 'university/TAIWAN/TW26.png'],
            ['english_name'=>'National Chiayi University', 'chinese_name'=>'國立嘉義大學', 'area' => 'COLLEGE', 'country'=>'TAIWAN', 'school_badge'=>'TW27', 'image_path' => 'university/TAIWAN/TW27.png'],
            ['english_name'=>'National University of Kaohsiung', 'chinese_name'=>'國立高雄大學', 'area' => 'COLLEGE', 'country'=>'TAIWAN', 'school_badge'=>'TW28', 'image_path' => 'university/TAIWAN/TW28.png'],
            ['english_name'=>'National Quemoy University', 'chinese_name'=>'國立金門大學', 'area' => 'COLLEGE', 'country'=>'TAIWAN', 'school_badge'=>'TW29', 'image_path' => 'university/TAIWAN/TW29.png'],
            ['english_name'=>'University of Taipei', 'chinese_name'=>'臺北市立大學', 'area' => 'COLLEGE', 'country'=>'TAIWAN', 'school_badge'=>'TW30', 'image_path' => 'university/TAIWAN/TW30.png'],
            ['english_name'=>'National Pingtung University', 'chinese_name'=>'國立屏東大學', 'area' => 'COLLEGE', 'country'=>'TAIWAN', 'school_badge'=>'TW31', 'image_path' => 'university/TAIWAN/TW31.png'],
            ['english_name'=>'National Yang Ming Chiao Tung University', 'chinese_name'=>'國立陽明交通大學', 'area' => 'COLLEGE', 'country'=>'TAIWAN', 'school_badge'=>'TW32', 'image_path' => 'university/TAIWAN/TW32.png'],
            ['english_name'=>'National Taiwan University of Science and Technology', 'chinese_name'=>'國立臺灣科技大學', 'area' => 'COLLEGE', 'country'=>'TAIWAN', 'school_badge'=>'TW33', 'image_path' => 'university/TAIWAN/TW33.png'],
            ['english_name'=>'National Yunlin University of Science and Technology', 'chinese_name'=>'國立雲林科技大學', 'area' => 'COLLEGE', 'country'=>'TAIWAN', 'school_badge'=>'TW34', 'image_path' => 'university/TAIWAN/TW34.png'],
            ['english_name'=>'National Pingtung University of Science and Technology', 'chinese_name'=>'國立屏東科技大學', 'area' => 'COLLEGE', 'country'=>'TAIWAN', 'school_badge'=>'TW35', 'image_path' => 'university/TAIWAN/TW35.png'],
            ['english_name'=>'National Taipei University of Technology', 'chinese_name'=>'國立臺北科技大學', 'area' => 'COLLEGE', 'country'=>'TAIWAN', 'school_badge'=>'TW36', 'image_path' => 'university/TAIWAN/TW36.png'],
            ['english_name'=>'National Taipei University of Nursing and Health Sciences', 'chinese_name'=>'國立臺北護理健康大學', 'area' => 'COLLEGE', 'country'=>'TAIWAN', 'school_badge'=>'TW37', 'image_path' => 'university/TAIWAN/TW37.png'],
            ['english_name'=>'National Formosa University', 'chinese_name'=>'國立虎尾科技大學', 'area' => 'COLLEGE', 'country'=>'TAIWAN', 'school_badge'=>'TW38', 'image_path' => 'university/TAIWAN/TW38.png'],
            ['english_name'=>'National Taichung University of Science and Technology', 'chinese_name'=>'國立臺中科技大學', 'area' => 'COLLEGE', 'country'=>'TAIWAN', 'school_badge'=>'TW39', 'image_path' => 'university/TAIWAN/TW39.png'],
            ['english_name'=>'National Chin-Yi University of Technology', 'chinese_name'=>'國立勤益科技大學', 'area' => 'COLLEGE', 'country'=>'TAIWAN', 'school_badge'=>'TW40', 'image_path' => 'university/TAIWAN/TW40.png'],
            ['english_name'=>'National Kaohsiung University of Hospitality and Tourism', 'chinese_name'=>'國立高雄餐旅大學', 'area' => 'COLLEGE', 'country'=>'TAIWAN', 'school_badge'=>'TW41', 'image_path' => 'university/TAIWAN/TW41.png'],
            ['english_name'=>'National Penghu University of Science and Technology', 'chinese_name'=>'國立澎湖科技大學', 'area' => 'COLLEGE', 'country'=>'TAIWAN', 'school_badge'=>'TW42', 'image_path' => 'university/TAIWAN/TW42.png'],
            ['english_name'=>'National Taipei University of Business', 'chinese_name'=>'國立臺北商業大學', 'area' => 'COLLEGE', 'country'=>'TAIWAN', 'school_badge'=>'TW43', 'image_path' => 'university/TAIWAN/TW43.png'],
            ['english_name'=>'National Kaohsiung University of Science and Technology', 'chinese_name'=>'國立高雄科技大學', 'area' => 'COLLEGE', 'country'=>'TAIWAN', 'school_badge'=>'TW44', 'image_path' => 'university/TAIWAN/TW44.png'],
            ['english_name'=>'Soochow University', 'chinese_name'=>'東吳大學', 'area' => 'COLLEGE', 'country'=>'TAIWAN', 'school_badge'=>'TW45', 'image_path' => 'university/TAIWAN/TW45.png'],
            ['english_name'=>'Kaohsiung Medical University', 'chinese_name'=>'高雄醫學大學', 'area' => 'COLLEGE', 'country'=>'TAIWAN', 'school_badge'=>'TW46', 'image_path' => 'university/TAIWAN/TW46.png'],
            ['english_name'=>'Tunghai University', 'chinese_name'=>'東海大學', 'area' => 'COLLEGE', 'country'=>'TAIWAN', 'school_badge'=>'TW47', 'image_path' => 'university/TAIWAN/TW47.png'],
            ['english_name'=>'Chung Yuan Christian University', 'chinese_name'=>'中原大學', 'area' => 'COLLEGE', 'country'=>'TAIWAN', 'school_badge'=>'TW48', 'image_path' => 'university/TAIWAN/TW48.png'],
            ['english_name'=>'Tamkang University', 'chinese_name'=>'淡江大學', 'area' => 'COLLEGE', 'country'=>'TAIWAN', 'school_badge'=>'TW49', 'image_path' => 'university/TAIWAN/TW49.png'],
            ['english_name'=>'China Medical University', 'chinese_name'=>'中國醫藥大學', 'area' => 'COLLEGE', 'country'=>'TAIWAN', 'school_badge'=>'TW50', 'image_path' => 'university/TAIWAN/TW50.png'],
            ['english_name'=>'Taipei Medical University', 'chinese_name'=>'臺北醫學大學', 'area' => 'COLLEGE', 'country'=>'TAIWAN', 'school_badge'=>'TW51', 'image_path' => 'university/TAIWAN/TW51.png'],
            ['english_name'=>'Fu Jen Catholic University', 'chinese_name'=>'天主教輔仁大學', 'area' => 'COLLEGE', 'country'=>'TAIWAN', 'school_badge'=>'TW52', 'image_path' => 'university/TAIWAN/TW52.png'],
            ['english_name'=>'Feng Chia University', 'chinese_name'=>'逢甲大學', 'area' => 'COLLEGE', 'country'=>'TAIWAN', 'school_badge'=>'TW53', 'image_path' => 'university/TAIWAN/TW53.png'],
            ['english_name'=>'Chinese Culture University', 'chinese_name'=>'中國文化大學', 'area' => 'COLLEGE', 'country'=>'TAIWAN', 'school_badge'=>'TW54', 'image_path' => 'university/TAIWAN/TW54.png'],
            ['english_name'=>'Tatung University', 'chinese_name'=>'大同大學', 'area' => 'COLLEGE', 'country'=>'TAIWAN', 'school_badge'=>'TW55', 'image_path' => 'university/TAIWAN/TW55.png'],
            ['english_name'=>'Chung Shan Medical University', 'chinese_name'=>'中山醫學大學', 'area' => 'COLLEGE', 'country'=>'TAIWAN', 'school_badge'=>'TW56', 'image_path' => 'university/TAIWAN/TW56.png'],
            ['english_name'=>'Yuan Ze University', 'chinese_name'=>'元智大學', 'area' => 'COLLEGE', 'country'=>'TAIWAN', 'school_badge'=>'TW57', 'image_path' => 'university/TAIWAN/TW57.png'],
            ['english_name'=>'Ming Chuan University', 'chinese_name'=>'銘傳大學', 'area' => 'COLLEGE', 'country'=>'TAIWAN', 'school_badge'=>'TW58', 'image_path' => 'university/TAIWAN/TW58.png'],
            ['english_name'=>'Chang Gung University', 'chinese_name'=>'長庚大學', 'area' => 'COLLEGE', 'country'=>'TAIWAN', 'school_badge'=>'TW59', 'image_path' => 'university/TAIWAN/TW59.png'],
            ['english_name'=>'Asia University', 'chinese_name'=>'亞洲大學', 'area' => 'COLLEGE', 'country'=>'TAIWAN', 'school_badge'=>'TW60', 'image_path' => 'university/TAIWAN/TW60.png'],
            ['english_name'=>'Tzu Chi University', 'chinese_name'=>'慈濟大學', 'area' => 'COLLEGE', 'country'=>'TAIWAN', 'school_badge'=>'TW61', 'image_path' => 'university/TAIWAN/TW61.png'],
            ['english_name'=>'Shih Chien University', 'chinese_name'=>'實踐大學', 'area' => 'COLLEGE', 'country'=>'TAIWAN', 'school_badge'=>'TW62', 'image_path' => 'university/TAIWAN/TW62.png'],
            ['english_name'=>'Shih Hsin University', 'chinese_name'=>'世新大學', 'area' => 'COLLEGE', 'country'=>'TAIWAN', 'school_badge'=>'TW63', 'image_path' => 'university/TAIWAN/TW63.png'],
            ['english_name'=>'Providence University', 'chinese_name'=>'靜宜大學', 'area' => 'COLLEGE', 'country'=>'TAIWAN', 'school_badge'=>'TW64', 'image_path' => 'university/TAIWAN/TW64.png'],
            ['english_name'=>'Mackay Medical College', 'chinese_name'=>'馬偕醫學院', 'area' => 'COLLEGE', 'country'=>'TAIWAN', 'school_badge'=>'TW65', 'image_path' => 'university/TAIWAN/TW65.png'],
            ['english_name'=>'Tainan University of Technology', 'chinese_name'=>'台南應用科技大學', 'area' => 'COLLEGE', 'country'=>'TAIWAN', 'school_badge'=>'TW66', 'image_path' => 'university/TAIWAN/TW66.png'],
            ['english_name'=>'Ling Tung University', 'chinese_name'=>'嶺東科技大學', 'area' => 'COLLEGE', 'country'=>'TAIWAN', 'school_badge'=>'TW67', 'image_path' => 'university/TAIWAN/TW67.png'],
            ['english_name'=>'Wenzao Ursuline University of Languages', 'chinese_name'=>'文藻外語大學', 'area' => 'COLLEGE', 'country'=>'TAIWAN', 'school_badge'=>'TW68', 'image_path' => 'university/TAIWAN/TW68.png'],
            ['english_name'=>'Kun Shan University', 'chinese_name'=>'崑山科技大學', 'area' => 'COLLEGE', 'country'=>'TAIWAN', 'school_badge'=>'TW69', 'image_path' => 'university/TAIWAN/TW69.png'],
            ['english_name'=>'Chaoyang University of Technology', 'chinese_name'=>'朝陽科技大學', 'area' => 'COLLEGE', 'country'=>'TAIWAN', 'school_badge'=>'TW70', 'image_path' => 'university/TAIWAN/TW70.png'],
            ['english_name'=>'Chung Hua University', 'chinese_name'=>'中華大學', 'area' => 'COLLEGE', 'country'=>'TAIWAN', 'school_badge'=>'TW71', 'image_path' => 'university/TAIWAN/TW71.png'],
            ['english_name'=>'I-SHOU University', 'chinese_name'=>'義守大學', 'area' => 'COLLEGE', 'country'=>'TAIWAN', 'school_badge'=>'TW72', 'image_path' => 'university/TAIWAN/TW72.png'],
            ['english_name'=>'Hungkuang University', 'chinese_name'=>'弘光科技大學', 'area' => 'COLLEGE', 'country'=>'TAIWAN', 'school_badge'=>'TW73', 'image_path' => 'university/TAIWAN/TW73.png'],
            ['english_name'=>'Shu-Te University', 'chinese_name'=>'樹德科技大學', 'area' => 'COLLEGE', 'country'=>'TAIWAN', 'school_badge'=>'TW74', 'image_path' => 'university/TAIWAN/TW74.png'],
            ['english_name'=>'Takming University of Science and Technology', 'chinese_name'=>'德明財經科技大學', 'area' => 'COLLEGE', 'country'=>'TAIWAN', 'school_badge'=>'TW75', 'image_path' => 'university/TAIWAN/TW75.png'],
            ['english_name'=>'R.O.C. Naval Academy', 'chinese_name'=>'中華民國海軍軍官學校', 'area' => 'COLLEGE', 'country'=>'TAIWAN', 'school_badge'=>'TW76', 'image_path' => 'university/TAIWAN/TW76.png'],
            ['english_name'=>'National Defense Medical Center', 'chinese_name'=>'國防醫學院', 'area' => 'COLLEGE', 'country'=>'TAIWAN', 'school_badge'=>'TW77', 'image_path' => 'university/TAIWAN/TW77.png'],
            ['english_name'=>'R.O.C. Air Force Academy', 'chinese_name'=>'中華民國空軍軍官學校', 'area' => 'COLLEGE', 'country'=>'TAIWAN', 'school_badge'=>'TW78', 'image_path' => 'university/TAIWAN/TW78.png'],
            ['english_name'=>'R.O.C. Military Academy', 'chinese_name'=>'中華民國陸軍軍官學校', 'area' => 'COLLEGE', 'country'=>'TAIWAN', 'school_badge'=>'TW79', 'image_path' => 'university/TAIWAN/TW79.png'],
            ['english_name'=>'National Defense University', 'chinese_name'=>'國防大學', 'area' => 'COLLEGE', 'country'=>'TAIWAN', 'school_badge'=>'TW80', 'image_path' => 'university/TAIWAN/TW80.png'],
            ['english_name'=>'R.O.C. Air Force Institute of Technology', 'chinese_name'=>'空軍航空技術學院', 'area' => 'COLLEGE', 'country'=>'TAIWAN', 'school_badge'=>'TW81', 'image_path' => 'university/TAIWAN/TW81.png'],
            ['english_name'=>'Central Police University', 'chinese_name'=>'中央警察大學', 'area' => 'COLLEGE', 'country'=>'TAIWAN', 'school_badge'=>'TW82', 'image_path' => 'university/TAIWAN/TW82.png'],
            ['english_name'=>'Taiwan Police College', 'chinese_name'=>'臺灣警察專科學校', 'area' => 'COLLEGE', 'country'=>'TAIWAN', 'school_badge'=>'TW83', 'image_path' => 'university/TAIWAN/TW83.png'],
        ];

        foreach($highschools as $highschool) {
            University::create([
                'slug' => str_slug($highschool['english_name']),
                'name' => $highschool['chinese_name'],
                'english_name' => $highschool['english_name'],
                'chinese_name' => $highschool['chinese_name'],
                'country' => $highschool['country'],
                'area' =>   $highschool['area'],
                'school_badge' => $highschool['school_badge'],
                'image_path' => $highschool['image_path'],
            ]);
        }

        foreach($university as $school) {
            University::create([
                'slug' => str_slug($school['english_name']),
                'name' => $school['chinese_name'],
                'english_name' => $school['english_name'],
                'chinese_name' => $school['chinese_name'],
                'country' => $school['country'],
                'area' =>   $school['area'],
                'school_badge' => $school['school_badge'],
                'image_path' => $school['image_path'],
            ]);
        }
    }
}
