<?php

use Illuminate\Database\Seeder;

class UniversitySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $universities = [
            ['english_name'=>'Harvard University','chinese_name'=>'哈佛大學','country'=>'USA','area'=>'NORTHEAST','state'=>'MA','school_badge'=>'US1'],
            ['english_name'=>'Princeton University','chinese_name'=>'普林斯頓大學','country'=>'USA','area'=>'NORTHEAST','state'=>'NJ','school_badge'=>'US2'],
            ['english_name'=>'Yale University','chinese_name'=>'耶魯大學','country'=>'USA','area'=>'NORTHEAST','state'=>'CT','school_badge'=>'US3'],
            ['english_name'=>'Massachusetts Institute of Technology','chinese_name'=>'麻省理工學院','country'=>'USA','area'=>'NORTHEAST','state'=>'MA','school_badge'=>'US4'],
            ['english_name'=>'Stanford University','chinese_name'=>'史丹福大學','country'=>'USA','area'=>'WEST','state'=>'CA','school_badge'=>'US5'],
            ['english_name'=>'California Institute of Technology','chinese_name'=>'加州理工學院','country'=>'USA','area'=>'WEST','state'=>'CA','school_badge'=>'US6'],
            ['english_name'=>'University of Pennsylvania','chinese_name'=>'賓夕法尼亞大學','country'=>'USA','area'=>'NORTHEAST','state'=>'PA','school_badge'=>'US7'],
            ['english_name'=>'Columbia University','chinese_name'=>'哥倫比亞大學','country'=>'USA','area'=>'NORTHEAST','state'=>'NY','school_badge'=>'US8'],
            ['english_name'=>'Duke University','chinese_name'=>'杜克大學','country'=>'USA','area'=>'SOUTH','state'=>'NC','school_badge'=>'US9'],
            ['english_name'=>'University of Chicago','chinese_name'=>'芝加哥大學','country'=>'USA','area'=>'MIDWEST','state'=>'IL','school_badge'=>'US10'],
            ['english_name'=>'Dartmouth College','chinese_name'=>'達特茅斯學院 ','country'=>'USA','area'=>'NORTHEAST','state'=>'NH','school_badge'=>'US11'],
            ['english_name'=>'Northwestern University','chinese_name'=>'西北大學','country'=>'USA','area'=>'MIDWEST','state'=>'IL','school_badge'=>'US12'],
            ['english_name'=>'Washington University in St. Louis','chinese_name'=>'聖路易斯華盛頓大學','country'=>'USA','area'=>'MIDWEST','state'=>'MO','school_badge'=>'US13'],
            ['english_name'=>'Cornell University','chinese_name'=>'康乃爾大學','country'=>'USA','area'=>'NORTHEAST','state'=>'NY','school_badge'=>'US14'],
            ['english_name'=>'Johns Hopkins University','chinese_name'=>'約翰霍普金斯大學','country'=>'USA','area'=>'SOUTH','state'=>'MD','school_badge'=>'US15'],
            ['english_name'=>'Brown University','chinese_name'=>'布朗大學','country'=>'USA','area'=>'NORTHEAST','state'=>'RI','school_badge'=>'US16'],
            ['english_name'=>'Rice University','chinese_name'=>'萊斯大學','country'=>'USA','area'=>'SOUTH','state'=>'TX','school_badge'=>'US17'],
            ['english_name'=>'Emory University','chinese_name'=>'埃默里大學','country'=>'USA','area'=>'SOUTH','state'=>'GA','school_badge'=>'US18'],
            ['english_name'=>'University of Notre Dame','chinese_name'=>'聖母大學','country'=>'USA','area'=>'MIDWEST','state'=>'IN','school_badge'=>'US19'],
            ['english_name'=>'Vanderbilt University','chinese_name'=>'範德比特大學','country'=>'USA','area'=>'SOUTH','state'=>'TN','school_badge'=>'US20'],
            ['english_name'=>'University of California Berkeley','chinese_name'=>'加州大學柏克萊分校','country'=>'USA','area'=>'WEST','state'=>'CA','school_badge'=>'US21'],
            ['english_name'=>'Carnegie Mellon University','chinese_name'=>'卡內基美隆大學','country'=>'USA','area'=>'NORTHEAST','state'=>'PA','school_badge'=>'US22'],
            ['english_name'=>'Georgetown University','chinese_name'=>'喬治城大學','country'=>'USA','area'=>'SOUTH','state'=>'DC','school_badge'=>'US23'],
            ['english_name'=>'University of Virginia','chinese_name'=>'維吉尼亞大學','country'=>'USA','area'=>'SOUTH','state'=>'VA','school_badge'=>'US24'],
            ['english_name'=>'University of California Los Angeles','chinese_name'=>'加州大學洛杉磯分校','country'=>'USA','area'=>'WEST','state'=>'CA','school_badge'=>'US25'],
            ['english_name'=>'University of Michigan Ann Arbor','chinese_name'=>'密西根大學安娜堡分校','country'=>'USA','area'=>'MIDWEST','state'=>'MI','school_badge'=>'US26'],
            ['english_name'=>'University of Southern California','chinese_name'=>'南加州大學','country'=>'USA','area'=>'WEST','state'=>'CA','school_badge'=>'US27'],
            ['english_name'=>'Tufts University','chinese_name'=>'塔夫斯大學','country'=>'USA','area'=>'NORTHEAST','state'=>'MA','school_badge'=>'US28'],
            ['english_name'=>'Wake Forest University','chinese_name'=>'維克森林大學','country'=>'USA','area'=>'SOUTH','state'=>'NC','school_badge'=>'US29'],
            ['english_name'=>'University of North Carolina Chapel Hill','chinese_name'=>'北卡羅來納大學教堂山分校','country'=>'USA','area'=>'SOUTH','state'=>'NC','school_badge'=>'US30'],
            ['english_name'=>'Brandeis University','chinese_name'=>'布蘭迪斯大學','country'=>'USA','area'=>'NORTHEAST','state'=>'MA','school_badge'=>'US31'],
            ['english_name'=>'College of William and Mary','chinese_name'=>'威廉與瑪麗學院 ','country'=>'USA','area'=>'SOUTH','state'=>'VA','school_badge'=>'US32'],
            ['english_name'=>'New York University','chinese_name'=>'紐約大學','country'=>'USA','area'=>'NORTHEAST','state'=>'NY','school_badge'=>'US33'],
            ['english_name'=>'Boston College','chinese_name'=>'波士頓學院','country'=>'USA','area'=>'NORTHEAST','state'=>'MA','school_badge'=>'US34'],
            ['english_name'=>'Georgia Institute of Technology','chinese_name'=>'喬治亞理工學院','country'=>'USA','area'=>'SOUTH','state'=>'GA','school_badge'=>'US35'],
            ['english_name'=>'Lehigh University','chinese_name'=>'里海大學','country'=>'USA','area'=>'NORTHEAST','state'=>'PA','school_badge'=>'US36'],
            ['english_name'=>'University of California San Diego','chinese_name'=>'加州大學聖地牙哥分校','country'=>'USA','area'=>'WEST','state'=>'CA','school_badge'=>'US37'],
            ['english_name'=>'University of Rochester','chinese_name'=>'羅徹斯特大學','country'=>'USA','area'=>'NORTHEAST','state'=>'NY','school_badge'=>'US38'],
            ['english_name'=>'University of Wisconsin Madison','chinese_name'=>'威斯康辛大學--麥迪森遜校','country'=>'USA','area'=>'MIDWEST','state'=>'WI','school_badge'=>'US39'],
            ['english_name'=>'University of Illinois Urbana Champaign','chinese_name'=>'伊利諾伊大學厄本那香檳分校','country'=>'USA','area'=>'MIDWEST','state'=>'IL','school_badge'=>'US40'],
            ['english_name'=>'Case Western Reserve University','chinese_name'=>'凱斯西儲大學','country'=>'USA','area'=>'MIDWEST','state'=>'OH','school_badge'=>'US41'],
            ['english_name'=>'Rensselaer Polytechnic Institute','chinese_name'=>'任色雷理工學院','country'=>'USA','area'=>'NORTHEAST','state'=>'NY','school_badge'=>'US42'],
            ['english_name'=>'University of Washington','chinese_name'=>'華盛頓大學','country'=>'USA','area'=>'WEST','state'=>'WA','school_badge'=>'US43'],
            ['english_name'=>'University of California Davis','chinese_name'=>'加州大學戴維斯分校','country'=>'USA','area'=>'WEST','state'=>'CA','school_badge'=>'US44'],
            ['english_name'=>'University of California Irvine','chinese_name'=>'加州大學爾灣分校','country'=>'USA','area'=>'WEST','state'=>'CA','school_badge'=>'US45'],
            ['english_name'=>'University of California Santa Barbara','chinese_name'=>'加州大學聖塔芭芭拉分校','country'=>'USA','area'=>'WEST','state'=>'CA','school_badge'=>'US46'],
            ['english_name'=>'Pennsylvania State University University Park','chinese_name'=>'賓州州立大學柏克校園','country'=>'USA','area'=>'NORTHEAST','state'=>'PA','school_badge'=>'US47'],
            ['english_name'=>'University of Texas Austin','chinese_name'=>'德州大學奧斯汀分校','country'=>'USA','area'=>'SOUTH','state'=>'TX','school_badge'=>'US48'],
            ['english_name'=>'University of Florida','chinese_name'=>'佛羅里達大學','country'=>'USA','area'=>'SOUTH','state'=>'FL','school_badge'=>'US49'],
            ['english_name'=>'Yeshiva University','chinese_name'=>'猶太大學','country'=>'USA','area'=>'NORTHEAST','state'=>'NY','school_badge'=>'US50'],
            ['english_name'=>'Tulane University','chinese_name'=>'杜蘭大學','country'=>'USA','area'=>'SOUTH','state'=>'LA','school_badge'=>'US51'],
            ['english_name'=>'University of Miami','chinese_name'=>'邁阿密大學','country'=>'USA','area'=>'SOUTH','state'=>'FL','school_badge'=>'US52'],
            ['english_name'=>'George Washington University','chinese_name'=>'喬治華盛頓大學','country'=>'USA','area'=>'SOUTH','state'=>'DC','school_badge'=>'US53'],
            ['english_name'=>'Syracuse University','chinese_name'=>'雪城大學','country'=>'USA','area'=>'NORTHEAST','state'=>'NY','school_badge'=>'US54'],
            ['english_name'=>'University of Maryland College Park','chinese_name'=>'馬里蘭大學大學園','country'=>'USA','area'=>'SOUTH','state'=>'MD','school_badge'=>'US55'],
            ['english_name'=>'Ohio State University Columbus','chinese_name'=>'俄亥俄州立大學哥倫比亞分校','country'=>'USA','area'=>'MIDWEST','state'=>'OH','school_badge'=>'US56'],
            ['english_name'=>'Pepperdine University','chinese_name'=>'佩波戴恩大學','country'=>'USA','area'=>'WEST','state'=>'CA','school_badge'=>'US57'],
            ['english_name'=>'University of Georgia','chinese_name'=>'喬治亞大學','country'=>'USA','area'=>'SOUTH','state'=>'GA','school_badge'=>'US58'],
            ['english_name'=>'University of Pittsburgh','chinese_name'=>'匹茲堡大學','country'=>'USA','area'=>'NORTHEAST','state'=>'PA','school_badge'=>'US59'],
            ['english_name'=>'Boston University','chinese_name'=>'波士頓大學','country'=>'USA','area'=>'NORTHEAST','state'=>'MA','school_badge'=>'US60'],
            ['english_name'=>'Clemson University','chinese_name'=>'克萊姆森大學','country'=>'USA','area'=>'SOUTH','state'=>'SC','school_badge'=>'US61'],
            ['english_name'=>'Fordham University','chinese_name'=>'福德漢姆大學','country'=>'USA','area'=>'NORTHEAST','state'=>'NY','school_badge'=>'US62'],
            ['english_name'=>'University of Minnesota Twin Cities ','chinese_name'=>'明尼蘇達大學雙城分校','country'=>'USA','area'=>'MIDWEST','state'=>'MN','school_badge'=>'US63'],
            ['english_name'=>'Rutgers the State University of New Jersey New Brunswick','chinese_name'=>'羅格斯大學新伯朗士威校區','country'=>'USA','area'=>'NORTHEAST','state'=>'NJ','school_badge'=>'US64'],
            ['english_name'=>'Texas A&M University College Station','chinese_name'=>'德州農工大學','country'=>'USA','area'=>'SOUTH','state'=>'TX','school_badge'=>'US65'],
            ['english_name'=>'Miami University Oxford','chinese_name'=>'邁阿密大學-牛津分校','country'=>'USA','area'=>'MIDWEST','state'=>'OH','school_badge'=>'US66'],
            ['english_name'=>'Purdue University West Lafayette','chinese_name'=>'普渡大學西拉法葉校區','country'=>'USA','area'=>'MIDWEST','state'=>'IN','school_badge'=>'US67'],
            ['english_name'=>'Southern Methodist University','chinese_name'=>'南衛理公會大學','country'=>'USA','area'=>'SOUTH','state'=>'TX','school_badge'=>'US68'],
            ['english_name'=>'University of Connecticut','chinese_name'=>'康乃狄克大學','country'=>'USA','area'=>'NORTHEAST','state'=>'CT','school_badge'=>'US69'],
            ['english_name'=>'University of Iowa','chinese_name'=>'愛荷華大學','country'=>'USA','area'=>'MIDWEST','state'=>'IA','school_badge'=>'US70'],
            ['english_name'=>'Indiana University Bloomington','chinese_name'=>'印地安那大學伯明頓分校','country'=>'USA','area'=>'MIDWEST','state'=>'IN','school_badge'=>'US71'],
            ['english_name'=>'Michigan State University','chinese_name'=>'密歇根州立大學','country'=>'USA','area'=>'MIDWEST','state'=>'MI','school_badge'=>'US72'],
            ['english_name'=>'University of Delaware','chinese_name'=>'美國德拉瓦大學','country'=>'USA','area'=>'SOUTH','state'=>'DE','school_badge'=>'US73'],
            ['english_name'=>'Virginia Tech','chinese_name'=>'佛吉尼亞理工大學','country'=>'USA','area'=>'SOUTH','state'=>'VA','school_badge'=>'US74'],
            ['english_name'=>'Worcester Polytechnic Institute','chinese_name'=>'伍斯特理工學院','country'=>'USA','area'=>'NORTHEAST','state'=>'MA','school_badge'=>'US75'],
            ['english_name'=>'Baylor University','chinese_name'=>'貝勒大學','country'=>'USA','area'=>'SOUTH','state'=>'TX','school_badge'=>'US76'],
            ['english_name'=>'Marquette University','chinese_name'=>'馬凱特大學','country'=>'USA','area'=>'MIDWEST','state'=>'WI','school_badge'=>'US77'],
            ['english_name'=>'SUNY Binghamton','chinese_name'=>'紐約州立大學賓厄姆頓分校','country'=>'USA','area'=>'NORTHEAST','state'=>'NY','school_badge'=>'US78'],
            ['english_name'=>'University of Colorado Boulder','chinese_name'=>'科羅拉多大學-波爾得分校','country'=>'USA','area'=>'WEST','state'=>'CO','school_badge'=>'US79'],
            ['english_name'=>'Clark University','chinese_name'=>'克拉克大學','country'=>'USA','area'=>'NORTHEAST','state'=>'MA','school_badge'=>'US80'],
            ['english_name'=>'Colorado School of Mines','chinese_name'=>'科羅拉多礦業學院','country'=>'USA','area'=>'WEST','state'=>'CO','school_badge'=>'US81'],
            ['english_name'=>'St. Louis University','chinese_name'=>'聖路易斯大學','country'=>'USA','area'=>'MIDWEST','state'=>'MO','school_badge'=>'US82'],
            ['english_name'=>'American University','chinese_name'=>'美國大學','country'=>'USA','area'=>'SOUTH','state'=>'DC','school_badge'=>'US83'],
            ['english_name'=>'North Carolina State University Raleigh ','chinese_name'=>'北卡羅來納州立大學','country'=>'USA','area'=>'SOUTH','state'=>'NC','school_badge'=>'US84'],
            ['english_name'=>'SUNY College of Environmental Science and Forestry ','chinese_name'=>'紐約州立大學環境科學與林業科學學院','country'=>'USA','area'=>'NORTHEAST','state'=>'NY','school_badge'=>'US85'],
            ['english_name'=>'Stevens Institute of Technology','chinese_name'=>'斯蒂文斯科技學院','country'=>'USA','area'=>'NORTHEAST','state'=>'NJ','school_badge'=>'US86'],
            ['english_name'=>'University of Alabama','chinese_name'=>'阿拉巴馬大學','country'=>'USA','area'=>'SOUTH','state'=>'AL','school_badge'=>'US87'],
            ['english_name'=>'University of Tulsa','chinese_name'=>'塔爾薩大學','country'=>'USA','area'=>'SOUTH','state'=>'OK','school_badge'=>'US88'],
            ['english_name'=>'Drexel University','chinese_name'=>'德雷塞爾大學','country'=>'USA','area'=>'NORTHEAST','state'=>'PA','school_badge'=>'US89'],
            ['english_name'=>'Iowa State University','chinese_name'=>'愛荷華州立大學','country'=>'USA','area'=>'MIDWEST','state'=>'IA','school_badge'=>'US90'],
            ['english_name'=>'University of California Riverside','chinese_name'=>'加州大學河濱分校','country'=>'USA','area'=>'WEST','state'=>'CA','school_badge'=>'US91'],
            ['english_name'=>'University of Denver','chinese_name'=>'丹佛大學','country'=>'USA','area'=>'WEST','state'=>'CO','school_badge'=>'US92'],
            ['english_name'=>'University of Kansas','chinese_name'=>'堪薩斯大學','country'=>'USA','area'=>'MIDWEST','state'=>'KS','school_badge'=>'US93'],
            ['english_name'=>'University of Nebraska Lincoln','chinese_name'=>'內布拉斯加大學林肯分校','country'=>'USA','area'=>'MIDWEST','state'=>'NE','school_badge'=>'US94'],
            ['english_name'=>'University of Vermont','chinese_name'=>'佛蒙特大學','country'=>'USA','area'=>'NORTHEAST','state'=>'VT','school_badge'=>'US95'],
            ['english_name'=>'Auburn University','chinese_name'=>'奧本大學','country'=>'USA','area'=>'SOUTH','state'=>'AL','school_badge'=>'US96'],
            ['english_name'=>'Northeastern University','chinese_name'=>'東北大學','country'=>'USA','area'=>'NORTHEAST','state'=>'MA','school_badge'=>'US97'],
            ['english_name'=>'SUNY Stony Brook','chinese_name'=>'紐約州立大學石溪分校','country'=>'USA','area'=>'NORTHEAST','state'=>'NY','school_badge'=>'US98'],
            ['english_name'=>'University of Arizona','chinese_name'=>'亞利桑那大學','country'=>'USA','area'=>'WEST','state'=>'AZ','school_badge'=>'US99'],
            ['english_name'=>'University of California Santa Cruz','chinese_name'=>'加州大學-聖塔克魯茲分校','country'=>'USA','area'=>'WEST','state'=>'CA','school_badge'=>'US100'],
            ['english_name'=>'University of Missouri Columbia','chinese_name'=>'密蘇裏大學哥倫比亞分校','country'=>'USA','area'=>'MIDWEST','state'=>'M0','school_badge'=>'US101'],
            ['english_name'=>'Academy of Art University','chinese_name'=>'舊金山藝術大學','country'=>'USA','area'=>'WEST','state'=>'CA','school_badge'=>'US102'],
            ['english_name'=>'SUNY Buffalo','chinese_name'=>'紐約州立大學水牛城分校','country'=>'USA','area'=>'NORTHEAST','state'=>'NY','school_badge'=>'US103'],
            ['english_name'=>'Rhode Island School of Design','chinese_name'=>'羅德島藝術學院','country'=>'USA','area'=>'NORTHEAST','state'=>'RI','school_badge'=>'US104'],
            ['english_name'=>'School of the Art Institute of Chicago','chinese_name'=>'芝加哥藝術學院','country'=>'USA','area'=>'MIDWEST','state'=>'IL','school_badge'=>'US105'],
            ['english_name'=>'Cranbrook University of Arts','chinese_name'=>'克蘭布魯克藝術學院','country'=>'USA','area'=>'NORTHEAST','state'=>'NY','school_badge'=>'US106'],
            ['english_name'=>'Virginia Commonwealth University','chinese_name'=>'維吉尼亞聯邦大學','country'=>'USA','area'=>'SOUTH','state'=>'VA','school_badge'=>'US107'],
            ['english_name'=>'Alfred University','chinese_name'=>'阿爾費德大學','country'=>'USA','area'=>'NORTHEAST','state'=>'NY','school_badge'=>'US108'],
            ['english_name'=>'California Institute of the Arts','chinese_name'=>'加州藝術學院','country'=>'USA','area'=>'WEST','state'=>'CA','school_badge'=>'US109'],
            ['english_name'=>'Maryland Institute College of Art','chinese_name'=>'馬里蘭藝術學院','country'=>'USA','area'=>'SOUTH','state'=>'MD','school_badge'=>'US110'],
            ['english_name'=>'Bard College','chinese_name'=>'巴德學院','country'=>'USA','area'=>'NORTHEAST','state'=>'NY','school_badge'=>'US111'],
            ['english_name'=>'California College of the Arts','chinese_name'=>'加州藝術學院','country'=>'USA','area'=>'WEST','state'=>'CA','school_badge'=>'US112'],
            ['english_name'=>'Pratt Institute','chinese_name'=>'普瑞特學院','country'=>'USA','area'=>'NORTHEAST','state'=>'NY','school_badge'=>'US113'],
            ['english_name'=>'Temple University','chinese_name'=>'天普大學','country'=>'USA','area'=>'NORTHEAST','state'=>'PA','school_badge'=>'US114'],
            ['english_name'=>'Arizona State University Tempe','chinese_name'=>'亞利桑那州立大學潭普分校','country'=>'USA','area'=>'WEST','state'=>'AZ','school_badge'=>'US115'],
            ['english_name'=>'Art Center College of Design','chinese_name'=>'藝術中心設計學院','country'=>'USA','area'=>'WEST','state'=>'CA','school_badge'=>'US116'],
            ['english_name'=>'CUNY Hunter College','chinese_name'=>'紐約市立大學杭特學院','country'=>'USA','area'=>'NORTHEAST','state'=>'NY','school_badge'=>'US117'],
            ['english_name'=>'School of Visual Arts','chinese_name'=>'視覺藝術學院','country'=>'USA','area'=>'NORTHEAST','state'=>'NY','school_badge'=>'US118'],
            ['english_name'=>'New School Parsons School of Design','chinese_name'=>'帕森斯設計學院','country'=>'USA','area'=>'NORTHEAST','state'=>'NY','school_badge'=>'US119'],
            ['english_name'=>'SUNY Purchase College','chinese_name'=>'紐約州立大學帕雀斯學院','country'=>'USA','area'=>'NORTHEAST','state'=>'NY','school_badge'=>'US120'],
            ['english_name'=>'OTIS College of Art and Design','chinese_name'=>'歐提斯藝術設計學院','country'=>'USA','area'=>'WEST','state'=>'CA','school_badge'=>'US121'],
            ['english_name'=>'Rochester Institute of Technology','chinese_name'=>'羅徹斯特理工學院','country'=>'USA','area'=>'NORTHEAST','state'=>'NY','school_badge'=>'US122'],
            ['english_name'=>'San Francisco Art Institute','chinese_name'=>'舊金山藝術學院','country'=>'USA','area'=>'WEST','state'=>'CA','school_badge'=>'US123'],
            ['english_name'=>'University of Tennessee Knoxville','chinese_name'=>'田納西大學諾克斯維爾校區','country'=>'USA','area'=>'SOUTH','state'=>'TN','school_badge'=>'US124'],
            ['english_name'=>'College for Creative Studies','chinese_name'=>'創意研究學院','country'=>'USA','area'=>'MIDWEST','state'=>'MI','school_badge'=>'US125'],
            ['english_name'=>'Massachusetts College of Art and Design','chinese_name'=>'麻州藝術設計學院','country'=>'USA','area'=>'NORTHEAST','state'=>'MA','school_badge'=>'US126'],
            ['english_name'=>'Minneapolis College of Art and Design','chinese_name'=>'明尼亞波理斯藝術設計學院','country'=>'USA','area'=>'MIDWEST','state'=>'MN','school_badge'=>'US127'],
            ['english_name'=>'SUNY Fashion Institution of Technology','chinese_name'=>'紐約時尚設計學院','country'=>'USA','area'=>'NORTHEAST','state'=>'NY','school_badge'=>'US128'],
            ['english_name'=>'Savannah College of Art and Design','chinese_name'=>'薩凡納藝術設計學院','country'=>'USA','area'=>'SOUTH','state'=>'GA','school_badge'=>'US129'],
            ['english_name'=>'Curtis Institute of Music','chinese_name'=>'柯蒂斯音樂學院','country'=>'USA','area'=>'NORTHEAST','state'=>'PA','school_badge'=>'US130'],
            ['english_name'=>'Berklee College of Music','chinese_name'=>'伯克利音樂學院','country'=>'USA','area'=>'NORTHEAST','state'=>'MA','school_badge'=>'US131'],
            ['english_name'=>'The Juilliard School','chinese_name'=>'茱莉亞音樂學院','country'=>'USA','area'=>'NORTHEAST','state'=>'NY','school_badge'=>'US132'],
            ['english_name'=>'San Francisco Conservatory of Music','chinese_name'=>'舊金山音樂學院','country'=>'USA','area'=>'WEST','state'=>'CA','school_badge'=>'US133'],
            ['english_name'=>'Cleveland Institute of Music','chinese_name'=>'克利夫蘭音樂學院','country'=>'USA','area'=>'MIDWEST','state'=>'OH','school_badge'=>'US134'],
            ['english_name'=>'New England Conservatory of Music','chinese_name'=>'新英格蘭音樂學院','country'=>'USA','area'=>'NORTHEAST','state'=>'MA','school_badge'=>'US135'],
            ['english_name'=>'Manhattan School of Music','chinese_name'=>'曼哈頓音樂學院','country'=>'USA','area'=>'NORTHEAST','state'=>'NY','school_badge'=>'US136'],
            ['english_name'=>'Musicians Institute','chinese_name'=>'美國流行音樂學院','country'=>'USA','area'=>'WEST','state'=>'CA','school_badge'=>'US137'],
            ['english_name'=>'Oberlin College','chinese_name'=>'歐柏林學院','country'=>'USA','area'=>'MIDWEST','state'=>'OH','school_badge'=>'US138'],
            ['english_name'=>'Los Angeles College of Music','chinese_name'=>'洛杉磯音樂學院','country'=>'USA','area'=>'WEST','state'=>'CA','school_badge'=>'US139'],
            ['english_name'=>'Lawrence University','chinese_name'=>'勞倫斯大學','country'=>'USA','area'=>'MIDWEST','state'=>'WI','school_badge'=>'US140'],
            ['english_name'=>'Wesleyan University','chinese_name'=>'維思大學','country'=>'USA','area'=>'NORTHEAST','state'=>'CT','school_badge'=>'US141'],
            ['english_name'=>'Brigham Young University','chinese_name'=>'楊百翰大學','country'=>'USA','area'=>'WEST','state'=>'UT','school_badge'=>'US142'],
            ['english_name'=>'Oklahoma City University','chinese_name'=>'俄克拉荷馬城大學','country'=>'USA','area'=>'SOUTH','state'=>'OK','school_badge'=>'US143'],
            ['english_name'=>'United States Coast Guard Academy','chinese_name'=>'美國海岸警衛隊學院','country'=>'USA','area'=>'NORTHEAST','state'=>'CT','school_badge'=>'US144'],
            ['english_name'=>'United States Merchant Marine Academy','chinese_name'=>'美國商船學院','country'=>'USA','area'=>'NORTHEAST','state'=>'NY','school_badge'=>'US145'],
            ['english_name'=>'United States Air Force Academy','chinese_name'=>'美國空軍學院','country'=>'USA','area'=>'WEST','state'=>'CO','school_badge'=>'US146'],
            ['english_name'=>'United States Naval Academy','chinese_name'=>'美國海軍學院','country'=>'USA','area'=>'SOUTH','state'=>'MD','school_badge'=>'US147'],
            ['english_name'=>'United States Military Academy','chinese_name'=>'美國軍事學院','country'=>'USA','area'=>'NORTHEAST','state'=>'NY','school_badge'=>'US148'],
            ['english_name'=>'CUNY Baruch College','chinese_name'=>'紐約市立大學柏魯克分校','country'=>'USA','area'=>'NORTHEAST','state'=>'NY','school_badge'=>'US149'],
            ['english_name'=>'SUNY New Paltz','chinese_name'=>'紐約州立大學紐伯茲分校','country'=>'USA','area'=>'NORTHEAST','state'=>'NY','school_badge'=>'US150'],
            ['english_name'=>'SUNY Albany','chinese_name'=>'紐約州立大學奧爾巴尼分校','country'=>'USA','area'=>'NORTHEAST','state'=>'NY','school_badge'=>'US151'],
            ['english_name'=>'SUNY Oswego','chinese_name'=>'紐約州立大學奧斯維格分校','country'=>'USA','area'=>'NORTHEAST','state'=>'NY','school_badge'=>'US152'],
//            ['english_name'=>'SUNY Binghamton','chinese_name'=>'紐約州立大學賓漢頓分校','country'=>'USA','area'=>'NORTHEAST','state'=>'NY','school_badge'=>'US153'],
            ['english_name'=>'University of Toronto','chinese_name'=>'多倫多大學','country'=>'CANADA','area'=>null,'state'=>null,'school_badge'=>'CA1'],
            ['english_name'=>'McGill University','chinese_name'=>'麥吉爾大學','country'=>'CANADA','area'=>null,'state'=>null,'school_badge'=>'CA2'],
            ['english_name'=>'University of British Columbia','chinese_name'=>'卑詩大學','country'=>'CANADA','area'=>null,'state'=>null,'school_badge'=>'CA3'],
            ['english_name'=>'University of Alberta','chinese_name'=>'亞伯塔大學','country'=>'CANADA','area'=>null,'state'=>null,'school_badge'=>'CA4'],
            ['english_name'=>'University of Montreal','chinese_name'=>'蒙特利爾大學','country'=>'CANADA','area'=>null,'state'=>null,'school_badge'=>'CA5'],
            ['english_name'=>'McMaster University','chinese_name'=>'麥克馬斯特大學','country'=>'CANADA','area'=>null,'state'=>null,'school_badge'=>'CA6'],
            ['english_name'=>'Western University','chinese_name'=>'西安大略大學','country'=>'CANADA','area'=>null,'state'=>null,'school_badge'=>'CA7'],
            ['english_name'=>'University of Calgary','chinese_name'=>'卡爾加里大學','country'=>'CANADA','area'=>null,'state'=>null,'school_badge'=>'CA8'],
            ['english_name'=>'University of Waterloo','chinese_name'=>'滑鐵盧大學','country'=>'CANADA','area'=>null,'state'=>null,'school_badge'=>'CA9'],
            ['english_name'=>'University of Ottawa','chinese_name'=>'渥太華大學','country'=>'CANADA','area'=>null,'state'=>null,'school_badge'=>'CA10'],
            ['english_name'=>'University of Manitoba','chinese_name'=>'曼尼托巴大學','country'=>'CANADA','area'=>null,'state'=>null,'school_badge'=>'CA11'],
            ['english_name'=>'Laval University','chinese_name'=>'拉瓦爾大學','country'=>'CANADA','area'=>null,'state'=>null,'school_badge'=>'CA12'],
            ['english_name'=>'Queen’s University','chinese_name'=>'女王大學','country'=>'CANADA','area'=>null,'state'=>null,'school_badge'=>'CA13'],
            ['english_name'=>'Dalhousie University','chinese_name'=>'達爾豪斯大學','country'=>'CANADA','area'=>null,'state'=>null,'school_badge'=>'CA14'],
            ['english_name'=>'Simon Fraser University','chinese_name'=>'西蒙菲莎大學','country'=>'CANADA','area'=>null,'state'=>null,'school_badge'=>'CA15'],
            ['english_name'=>'University of Saskatchewan','chinese_name'=>'薩斯喀徹温大學','country'=>'CANADA','area'=>null,'state'=>null,'school_badge'=>'CA16'],
            ['english_name'=>'University of Victoria','chinese_name'=>'維多利亞大學','country'=>'CANADA','area'=>null,'state'=>null,'school_badge'=>'CA17'],
            ['english_name'=>'York University','chinese_name'=>'約克大學','country'=>'CANADA','area'=>null,'state'=>null,'school_badge'=>'CA18'],
            ['english_name'=>'University of Guelph','chinese_name'=>'貴湖大學','country'=>'CANADA','area'=>null,'state'=>null,'school_badge'=>'CA19'],
            ['english_name'=>'Carleton University','chinese_name'=>'卡爾頓大學','country'=>'CANADA','area'=>null,'state'=>null,'school_badge'=>'CA20'],
            ['english_name'=>'Sheridan College','chinese_name'=>'謝爾丹學院','country'=>'CANADA','area'=>null,'state'=>null,'school_badge'=>'CA21'],
            ['english_name'=>'Emily Carr University of Art + Design','chinese_name'=>'艾米麗卡爾藝術與設計大學','country'=>'CANADA','area'=>null,'state'=>null,'school_badge'=>'CA22'],
            ['english_name'=>'NSCAD University','chinese_name'=>'諾瓦藝術與設計大學','country'=>'CANADA','area'=>null,'state'=>null,'school_badge'=>'CA23'],
            ['english_name'=>'ALBERTA COLLEGE OF ARTS AND DESIGN','chinese_name'=>'亞伯塔藝術設計學院','country'=>'CANADA','area'=>null,'state'=>null,'school_badge'=>'CA24'],
            ['english_name'=>'Ontario College of Art and Design','chinese_name'=>'安大略藝術與設計學院','country'=>'CANADA','area'=>null,'state'=>null,'school_badge'=>'CA25'],
            ['english_name'=>'Vancouver Film School','chinese_name'=>'溫哥華電影學院','country'=>'CANADA','area'=>null,'state'=>null,'school_badge'=>'CA26'],
            ['english_name'=>'Toronto Film School','chinese_name'=>'多倫多電影學院','country'=>'CANADA','area'=>null,'state'=>null,'school_badge'=>'CA27'],
            ['english_name'=>'The Royal Conservatory of Music','chinese_name'=>'加拿大皇家音樂學院','country'=>'CANADA','area'=>null,'state'=>null,'school_badge'=>'CA28'],
            ['english_name'=>'Brandon University','chinese_name'=>'布蘭登大學','country'=>'CANADA','area'=>null,'state'=>null,'school_badge'=>'CA29'],
            ['english_name'=>'University of Cambridge','chinese_name'=>'劍橋大學','country'=>'UK','area'=>null,'state'=>null,'school_badge'=>'UK1'],
            ['english_name'=>'University of Oxford','chinese_name'=>'牛津大學','country'=>'UK','area'=>null,'state'=>null,'school_badge'=>'UK2'],
            ['english_name'=>'Imperial College London','chinese_name'=>'帝國理工大學','country'=>'UK','area'=>null,'state'=>null,'school_badge'=>'UK3'],
            ['english_name'=>'University College London','chinese_name'=>'倫敦大學學院','country'=>'UK','area'=>null,'state'=>null,'school_badge'=>'UK4'],
            ['english_name'=>'The University of Edinburgh','chinese_name'=>'愛丁堡大學','country'=>'UK','area'=>null,'state'=>null,'school_badge'=>'UK5'],
            ['english_name'=>'The University of Manchester','chinese_name'=>'曼徹斯特大學','country'=>'UK','area'=>null,'state'=>null,'school_badge'=>'UK6'],
            ['english_name'=>'Kings College London','chinese_name'=>'倫敦國王學院','country'=>'UK','area'=>null,'state'=>null,'school_badge'=>'UK7'],
            ['english_name'=>'The London School of Economics and Political Science','chinese_name'=>'倫敦政經學院','country'=>'UK','area'=>null,'state'=>null,'school_badge'=>'UK8'],
            ['english_name'=>'University of Bristol','chinese_name'=>'布里斯托大學','country'=>'UK','area'=>null,'state'=>null,'school_badge'=>'UK9'],
            ['english_name'=>'The University of Warwick','chinese_name'=>'華威大學','country'=>'UK','area'=>null,'state'=>null,'school_badge'=>'UK10'],
            ['english_name'=>'University of Southampton','chinese_name'=>'南安普敦大學','country'=>'UK','area'=>null,'state'=>null,'school_badge'=>'UK11'],
            ['english_name'=>'University of Glasgow','chinese_name'=>'格拉斯哥大學','country'=>'UK','area'=>null,'state'=>null,'school_badge'=>'UK12'],
            ['english_name'=>'University of Leeds','chinese_name'=>'里茲大學','country'=>'UK','area'=>null,'state'=>null,'school_badge'=>'UK13'],
            ['english_name'=>'University of Birmingham','chinese_name'=>'伯明罕大學','country'=>'UK','area'=>null,'state'=>null,'school_badge'=>'UK14'],
            ['english_name'=>'Durham University','chinese_name'=>'杜倫大學','country'=>'UK','area'=>null,'state'=>null,'school_badge'=>'UK15'],
            ['english_name'=>'The University of Sheffield','chinese_name'=>'雪菲爾大學','country'=>'UK','area'=>null,'state'=>null,'school_badge'=>'UK16'],
            ['english_name'=>'University of St Andrews','chinese_name'=>'聖安德魯大學','country'=>'UK','area'=>null,'state'=>null,'school_badge'=>'UK17'],
            ['english_name'=>'University of Bath','chinese_name'=>'巴斯大學','country'=>'UK','area'=>null,'state'=>null,'school_badge'=>'UK18'],
            ['english_name'=>'Loughborough University','chinese_name'=>'羅浮堡大學','country'=>'UK','area'=>null,'state'=>null,'school_badge'=>'UK19'],
            ['english_name'=>'University of Aberdeen','chinese_name'=>'阿伯丁大學','country'=>'UK','area'=>null,'state'=>null,'school_badge'=>'UK20'],
            ['english_name'=>'Lancaster University','chinese_name'=>'蘭卡斯特大學','country'=>'UK','area'=>null,'state'=>null,'school_badge'=>'UK21'],
            ['english_name'=>'University of Exeter','chinese_name'=>'埃克塞特大學','country'=>'UK','area'=>null,'state'=>null,'school_badge'=>'UK22'],
//            ['english_name'=>'University of Southampton','chinese_name'=>'南安普敦大學','country'=>'UK','area'=>null,'state'=>null,'school_badge'=>'UK23'],
            ['english_name'=>'University of Strathclyde','chinese_name'=>'斯特拉斯克萊德大學','country'=>'UK','area'=>null,'state'=>null,'school_badge'=>'UK24'],
            ['english_name'=>'University of the Arts London','chinese_name'=>'倫敦藝術大學','country'=>'UK','area'=>null,'state'=>null,'school_badge'=>'UK25'],
            ['english_name'=>'University of York','chinese_name'=>'約克大學','country'=>'UK','area'=>null,'state'=>null,'school_badge'=>'UK26'],
            ['english_name'=>'Royal College of Art','chinese_name'=>'皇家藝術學院','country'=>'UK','area'=>null,'state'=>null,'school_badge'=>'UK27'],
            ['english_name'=>'Glasgow School of Art','chinese_name'=>'格拉斯哥藝術學院','country'=>'UK','area'=>null,'state'=>null,'school_badge'=>'UK28'],
            ['english_name'=>'Kingston University ','chinese_name'=>'金斯頓大學','country'=>'UK','area'=>null,'state'=>null,'school_badge'=>'UK29'],
            ['english_name'=>'Goldsmith University of London','chinese_name'=>'金匠大學','country'=>'UK','area'=>null,'state'=>null,'school_badge'=>'UK30'],
            ['english_name'=>'CSVPA','chinese_name'=>'劍橋視覺藝術表演學校','country'=>'UK','area'=>null,'state'=>null,'school_badge'=>'UK31'],
            ['english_name'=>'Australian National University','chinese_name'=>'澳洲國立大學','country'=>'AUSTRALIA','area'=>null,'state'=>null,'school_badge'=>'AU1'],
            ['english_name'=>'The University of Melbourne','chinese_name'=>'墨爾本大學','country'=>'AUSTRALIA','area'=>null,'state'=>null,'school_badge'=>'AU2'],
            ['english_name'=>'The University of Sydney','chinese_name'=>'雪梨大學','country'=>'AUSTRALIA','area'=>null,'state'=>null,'school_badge'=>'AU3'],
            ['english_name'=>'The University of New South Wales ','chinese_name'=>'新南威爾斯大學','country'=>'AUSTRALIA','area'=>null,'state'=>null,'school_badge'=>'AU4'],
            ['english_name'=>'The University of Queensland','chinese_name'=>'昆士蘭大學','country'=>'AUSTRALIA','area'=>null,'state'=>null,'school_badge'=>'AU5'],
            ['english_name'=>'Monash University','chinese_name'=>'蒙納許大學','country'=>'AUSTRALIA','area'=>null,'state'=>null,'school_badge'=>'AU6'],
            ['english_name'=>'The University of Western Australia','chinese_name'=>'西澳大學','country'=>'AUSTRALIA','area'=>null,'state'=>null,'school_badge'=>'AU7'],
            ['english_name'=>'The University of Adelaide','chinese_name'=>'阿得雷德大學','country'=>'AUSTRALIA','area'=>null,'state'=>null,'school_badge'=>'AU8'],
            ['english_name'=>'University of Wollongong','chinese_name'=>'臥龍崗大學','country'=>'AUSTRALIA','area'=>null,'state'=>null,'school_badge'=>'AU9'],
            ['english_name'=>'RMIT University','chinese_name'=>'皇家墨爾本理工大學','country'=>'AUSTRALIA','area'=>null,'state'=>null,'school_badge'=>'AU10'],
            ['english_name'=>'The University of Newcastle, Australia ','chinese_name'=>'紐卡素大學','country'=>'AUSTRALIA','area'=>null,'state'=>null,'school_badge'=>'AU11'],
            ['english_name'=>'Curtin University','chinese_name'=>'科廷大學','country'=>'AUSTRALIA','area'=>null,'state'=>null,'school_badge'=>'AU12'],
            ['english_name'=>'Macquarie University','chinese_name'=>'麥考瑞大學','country'=>'AUSTRALIA','area'=>null,'state'=>null,'school_badge'=>'AU13'],
            ['english_name'=>'Queensland University of Technology ','chinese_name'=>'昆士蘭科技大學','country'=>'AUSTRALIA','area'=>null,'state'=>null,'school_badge'=>'AU14'],
            ['english_name'=>'Deakin University','chinese_name'=>'迪肯大學','country'=>'AUSTRALIA','area'=>null,'state'=>null,'school_badge'=>'AU15'],
            ['english_name'=>'University of Tasmania','chinese_name'=>'塔斯馬尼亞大學','country'=>'AUSTRALIA','area'=>null,'state'=>null,'school_badge'=>'AU16'],
            ['english_name'=>'Swinburne University of Technology','chinese_name'=>'斯威本科技大學','country'=>'AUSTRALIA','area'=>null,'state'=>null,'school_badge'=>'AU17'],
            ['english_name'=>'Griffith University','chinese_name'=>'格里菲斯大學','country'=>'AUSTRALIA','area'=>null,'state'=>null,'school_badge'=>'AU18'],
            ['english_name'=>'La Trobe University','chinese_name'=>'拉籌伯大學','country'=>'AUSTRALIA','area'=>null,'state'=>null,'school_badge'=>'AU19'],
            ['english_name'=>'University of South Australia','chinese_name'=>'南澳大學','country'=>'AUSTRALIA','area'=>null,'state'=>null,'school_badge'=>'AU20'],
            ['english_name'=>'James Cook University','chinese_name'=>'詹姆斯庫克大學','country'=>'AUSTRALIA','area'=>null,'state'=>null,'school_badge'=>'AU21'],
            ['english_name'=>'Bond University','chinese_name'=>'龐德大學','country'=>'AUSTRALIA','area'=>null,'state'=>null,'school_badge'=>'AU22'],
            ['english_name'=>'Western Sydney University','chinese_name'=>'西雪梨大學','country'=>'AUSTRALIA','area'=>null,'state'=>null,'school_badge'=>'AU23'],
            ['english_name'=>'University of Canberra','chinese_name'=>'坎培拉大學','country'=>'AUSTRALIA','area'=>null,'state'=>null,'school_badge'=>'AU24'],
            ['english_name'=>'Murdoch University','chinese_name'=>'梅鐸大學','country'=>'AUSTRALIA','area'=>null,'state'=>null,'school_badge'=>'AU25'],
            ['english_name'=>'Central Queensland University ','chinese_name'=>'南昆士蘭大學','country'=>'AUSTRALIA','area'=>null,'state'=>null,'school_badge'=>'AU26'],
            ['english_name'=>'Australian Catholic University','chinese_name'=>'澳洲天主教大學','country'=>'AUSTRALIA','area'=>null,'state'=>null,'school_badge'=>'AU27'],
            ['english_name'=>'The university of Auckland','chinese_name'=>'奧克蘭大學','country'=>'NEW ZEALAND','area'=>null,'state'=>null,'school_badge'=>'NZ1'],
            ['english_name'=>'University of Otago','chinese_name'=>'奧塔哥大學','country'=>'NEW ZEEALAND','area'=>null,'state'=>null,'school_badge'=>'NZ2'],
            ['english_name'=>'Victoria University of Wellington','chinese_name'=>'威靈頓維多利亞大學','country'=>'NEW ZEALAND','area'=>null,'state'=>null,'school_badge'=>'NZ3'],
            ['english_name'=>'University of Canterbury','chinese_name'=>'坎特伯雷大學','country'=>'NEW ZEEALAND','area'=>null,'state'=>null,'school_badge'=>'NZ4'],
            ['english_name'=>'Massey University','chinese_name'=>'梅西大學','country'=>'NEW ZEALAND','area'=>null,'state'=>null,'school_badge'=>'NZ5'],
            ['english_name'=>'University of Waikato','chinese_name'=>'懷卡託大學','country'=>'NEW ZEEALAND','area'=>null,'state'=>null,'school_badge'=>'NZ6'],
            ['english_name'=>'Lincoln University','chinese_name'=>'林肯大學','country'=>'NEW ZEALAND','area'=>null,'state'=>null,'school_badge'=>'NZ7'],
            ['english_name'=>'Auckland University of Technology','chinese_name'=>'奧克蘭理工大學','country'=>'NEW ZEEALAND','area'=>null,'state'=>null,'school_badge'=>'NZ8'],
            ['english_name'=>'Technical University of Munich','chinese_name'=>'慕尼黑工業大學','country'=>'GERMANY','area'=>null,'state'=>null,'school_badge'=>'GE1'],
            ['english_name'=>'University of Munich','chinese_name'=>'慕尼黑大學','country'=>'GERMANY','area'=>null,'state'=>null,'school_badge'=>'GE2'],
            ['english_name'=>'Heidelberg University','chinese_name'=>'海德堡大學','country'=>'GERMANY','area'=>null,'state'=>null,'school_badge'=>'GE3'],
            ['english_name'=>'Charité - Universitätsmedizin Berlin','chinese_name'=>'柏林大學醫學院 ','country'=>'GERMANY','area'=>null,'state'=>null,'school_badge'=>'GE4'],
            ['english_name'=>'University of Tuebingen','chinese_name'=>'圖賓根大學','country'=>'GERMANY','area'=>null,'state'=>null,'school_badge'=>'GE5'],
            ['english_name'=>'Humboldt University of Berlin','chinese_name'=>'柏林洪堡大學','country'=>'GERMANY','area'=>null,'state'=>null,'school_badge'=>'GE6'],
            ['english_name'=>'University of Bonn','chinese_name'=>'波恩大學','country'=>'GERMANY','area'=>null,'state'=>null,'school_badge'=>'GE7'],
            ['english_name'=>'Free University of Berlin','chinese_name'=>'柏林自由大學','country'=>'GERMANY','area'=>null,'state'=>null,'school_badge'=>'GE8'],
            ['english_name'=>'Rwth Aachen University','chinese_name'=>'亞琛工業大學 ','country'=>'GERMANY','area'=>null,'state'=>null,'school_badge'=>'GE9'],
            ['english_name'=>'University of Freiburg','chinese_name'=>'弗萊堡大學','country'=>'GERMANY','area'=>null,'state'=>null,'school_badge'=>'GE10'],
            ['english_name'=>'University of Goettingen','chinese_name'=>'哥廷根大學','country'=>'GERMANY','area'=>null,'state'=>null,'school_badge'=>'GE11'],
            ['english_name'=>'University of Hamburg','chinese_name'=>'漢堡大學','country'=>'GERMANY','area'=>null,'state'=>null,'school_badge'=>'GE12'],
            ['english_name'=>'University of Wuerzburg','chinese_name'=>'維爾茨堡大學','country'=>'GERMANY','area'=>null,'state'=>null,'school_badge'=>'GE13'],
            ['english_name'=>'University of Cologne','chinese_name'=>'科隆大學 ','country'=>'GERMANY','area'=>null,'state'=>null,'school_badge'=>'GE14'],
            ['english_name'=>'University of Ulm','chinese_name'=>'烏爾姆大學','country'=>'GERMANY','area'=>null,'state'=>null,'school_badge'=>'GE15'],
            ['english_name'=>'Dresden University of Technology','chinese_name'=>'德累斯頓工業大學 ','country'=>'GERMANY','area'=>null,'state'=>null,'school_badge'=>'GE16'],
            ['english_name'=>'Technical University of Berlin','chinese_name'=>'柏林工業大學','country'=>'GERMANY','area'=>null,'state'=>null,'school_badge'=>'GE17'],
            ['english_name'=>'Universität Mannheim','chinese_name'=>'曼海姆大學','country'=>'GERMANY','area'=>null,'state'=>null,'school_badge'=>'GE18'],
            ['english_name'=>'University of Muenster','chinese_name'=>'明斯特大學','country'=>'GERMANY','area'=>null,'state'=>null,'school_badge'=>'GE19'],
            ['english_name'=>'Karlsruhe Institute of Technology','chinese_name'=>'卡爾斯魯厄理工學院','country'=>'GERMANY','area'=>null,'state'=>null,'school_badge'=>'GE20'],
            ['english_name'=>'ESMT','chinese_name'=>'柏林商學院','country'=>'GERMANY','area'=>null,'state'=>null,'school_badge'=>'GE21'],
            ['english_name'=>'SORBONNE UNIVERSITE','chinese_name'=>'索邦大學','country'=>'FRANCE','area'=>null,'state'=>null,'school_badge'=>'FR1'],
            ['english_name'=>'UNIVERSITE DE PARIS','chinese_name'=>'巴黎大學','country'=>'FRANCE','area'=>null,'state'=>null,'school_badge'=>'FR2'],
            ['english_name'=>'NIVERSITY OF PARIS DIDEROT','chinese_name'=>'巴黎第七大學','country'=>'FRANCE','area'=>null,'state'=>null,'school_badge'=>'FR3'],
            ['english_name'=>'UNIVERSITE DE TOULOUSE','chinese_name'=>'圖盧茲大學','country'=>'FRANCE','area'=>null,'state'=>null,'school_badge'=>'FR4'],
            ['english_name'=>'AIX-MARSEILLE UNIVERSITE','chinese_name'=>'艾克斯-馬賽大學','country'=>'FRANCE','area'=>null,'state'=>null,'school_badge'=>'FR5'],
            ['english_name'=>'UNIVERSITE GRENOBLE ALPES ','chinese_name'=>'格勒諾布爾-阿爾卑斯大學','country'=>'FRANCE','area'=>null,'state'=>null,'school_badge'=>'FR6'],
            ['english_name'=>'UNIVERSITE DE BORDEAUX','chinese_name'=>'波爾多大學','country'=>'FRANCE','area'=>null,'state'=>null,'school_badge'=>'FR7'],
            ['english_name'=>'UNIVERSITE DE STRASBOURG','chinese_name'=>'斯特拉斯堡大學','country'=>'FRANCE','area'=>null,'state'=>null,'school_badge'=>'FR8'],
            ['english_name'=>'UNIVERSITE DE MONTPELLIER','chinese_name'=>'蒙彼利埃大學','country'=>'FRANCE','area'=>null,'state'=>null,'school_badge'=>'FR9'],
            ['english_name'=>'UNIVERSITE TOULOUSE III - PAUL SABATIER','chinese_name'=>'圖盧茲第三大學','country'=>'FRANCE','area'=>null,'state'=>null,'school_badge'=>'FR10'],
            ['english_name'=>'COMMUNAUTE UNIVERSITE GRENOBLE ALPES','chinese_name'=>'格勒諾布爾阿爾卑斯公社大學','country'=>'FRANCE','area'=>null,'state'=>null,'school_badge'=>'FR11'],
            ['english_name'=>'UNIVERSITY OF PARIS DESCARTES','chinese_name'=>'巴黎第五大學','country'=>'FRANCE','area'=>null,'state'=>null,'school_badge'=>'FR12'],
            ['english_name'=>'UNIVERSITE DE LILLE','chinese_name'=>'里爾大學','country'=>'FRANCE','area'=>null,'state'=>null,'school_badge'=>'FR13'],
            ['english_name'=>'UNIVERSITE CLAUDE BERNARD LYON 1','chinese_name'=>'里昂第一大學','country'=>'FRANCE','area'=>null,'state'=>null,'school_badge'=>'FR14'],
            ['english_name'=>'UNIVERSITE DE LORRAINE','chinese_name'=>'洛林大學','country'=>'FRANCE','area'=>null,'state'=>null,'school_badge'=>'FR15'],
            ['english_name'=>'UNIV BOURGOGNE FRANCHE-COMTE COMUE','chinese_name'=>'勃艮第弗朗什孔泰大學','country'=>'FRANCE','area'=>null,'state'=>null,'school_badge'=>'FR16'],
            ['english_name'=>'UNIVERSITE DE NANTES','chinese_name'=>'南特大學','country'=>'FRANCE','area'=>null,'state'=>null,'school_badge'=>'FR17'],
            ['english_name'=>'UNIVERSITE DE VERSAILLES SAINT-QUENTIN-EN-YVELINES','chinese_name'=>'凡爾賽大學','country'=>'FRANCE','area'=>null,'state'=>null,'school_badge'=>'FR18'],
            ['english_name'=>'UNIVERSITE DE RENNES 1','chinese_name'=>'雷恩第一大學','country'=>'FRANCE','area'=>null,'state'=>null,'school_badge'=>'FR19'],
            ['english_name'=>'HEC','chinese_name'=>'巴黎高等商學院','country'=>'FRANCE','area'=>null,'state'=>null,'school_badge'=>'FR20'],
            ['english_name'=>'Insead','chinese_name'=>'歐洲工商管理學院','country'=>'FRANCE','area'=>null,'state'=>null,'school_badge'=>'FR21'],
            ['english_name'=>'Essec','chinese_name'=>'高等經濟商業學院','country'=>'FRANCE','area'=>null,'state'=>null,'school_badge'=>'FR22'],
            ['english_name'=>'EDHEC','chinese_name'=>'北方高等商學院','country'=>'FRANCE','area'=>null,'state'=>null,'school_badge'=>'FR23'],
            ['english_name'=>'Emlyon Business School','chinese_name'=>'里昂商學院','country'=>'FRANCE','area'=>null,'state'=>null,'school_badge'=>'FR24'],
            ['english_name'=>'ESCP','chinese_name'=>'歐洲高等商學院','country'=>'FRANCE','area'=>null,'state'=>null,'school_badge'=>'FR25'],
            ['english_name'=>'UNIVERSITY OF TOKYO','chinese_name'=>'東京大學','country'=>'JAPAN','area'=>null,'state'=>null,'school_badge'=>'JP1'],
            ['english_name'=>'KYOTO UNIVERSITY','chinese_name'=>'京都大學','country'=>'JAPAN','area'=>null,'state'=>null,'school_badge'=>'JP2'],
            ['english_name'=>'NAGOYA UNIVERSITY','chinese_name'=>'名古屋大學','country'=>'JAPAN','area'=>null,'state'=>null,'school_badge'=>'JP3'],
            ['english_name'=>'TOHOKU UNIVERSITY','chinese_name'=>'日本東北大學','country'=>'JAPAN','area'=>null,'state'=>null,'school_badge'=>'JP4'],
            ['english_name'=>'OSAKA UNIVERSITY','chinese_name'=>'大阪大學','country'=>'JAPAN','area'=>null,'state'=>null,'school_badge'=>'JP5'],
            ['english_name'=>'TOKYO INSTITUTE OF TECHNOLOGY','chinese_name'=>'東京工業大學','country'=>'JAPAN','area'=>null,'state'=>null,'school_badge'=>'JP6'],
            ['english_name'=>'KYUSHU UNIVERSITY','chinese_name'=>'九州大學','country'=>'JAPAN','area'=>null,'state'=>null,'school_badge'=>'JP7'],
            ['english_name'=>'HOKKAIDO UNIVERSITY','chinese_name'=>'北海道大學','country'=>'JAPAN','area'=>null,'state'=>null,'school_badge'=>'JP8'],
            ['english_name'=>'UNIVERSITY OF TSUKUBA','chinese_name'=>'築波大學','country'=>'JAPAN','area'=>null,'state'=>null,'school_badge'=>'JP9'],
            ['english_name'=>'KEIO UNIVERSITY','chinese_name'=>'慶應義塾大學','country'=>'JAPAN','area'=>null,'state'=>null,'school_badge'=>'JP10'],
            ['english_name'=>'HIROSHIMA UNIVERSITY','chinese_name'=>'廣島大學','country'=>'JAPAN','area'=>null,'state'=>null,'school_badge'=>'JP11'],
            ['english_name'=>'OKAYAMA UNIVERSITY','chinese_name'=>'岡山大學','country'=>'JAPAN','area'=>null,'state'=>null,'school_badge'=>'JP12'],
            ['english_name'=>'SHINSHU UNIVERSITY','chinese_name'=>'信州大學','country'=>'JAPAN','area'=>null,'state'=>null,'school_badge'=>'JP13'],
            ['english_name'=>'KOBE UNIVERSITY','chinese_name'=>'神戶大學','country'=>'JAPAN','area'=>null,'state'=>null,'school_badge'=>'JP14'],
            ['english_name'=>'WASEDA UNIVERSITY','chinese_name'=>'早稻田大學','country'=>'JAPAN','area'=>null,'state'=>null,'school_badge'=>'JP15'],
            ['english_name'=>'CHIBA UNIVERSITY','chinese_name'=>'千葉大學','country'=>'JAPAN','area'=>null,'state'=>null,'school_badge'=>'JP16'],
            ['english_name'=>'TOKYO METROPOLITAN UNIVERSITY','chinese_name'=>'東京都立大學','country'=>'JAPAN','area'=>null,'state'=>null,'school_badge'=>'JP17'],
            ['english_name'=>'KANAZAWA UNIVERSITY','chinese_name'=>'金澤大學','country'=>'JAPAN','area'=>null,'state'=>null,'school_badge'=>'JP18'],
            ['english_name'=>'TOKYO MEDICAL & DENTAL UNIVERSITY','chinese_name'=>'東京醫科齒科大學','country'=>'JAPAN','area'=>null,'state'=>null,'school_badge'=>'JP19'],
            ['english_name'=>'TOKYO UNIVERSITY OF SCIENCE','chinese_name'=>'東京理科大學','country'=>'JAPAN','area'=>null,'state'=>null,'school_badge'=>'JP20'],
            ['english_name'=>'TOKUSHIMA UNIVERSITY','chinese_name'=>'德島大學','country'=>'JAPAN','area'=>null,'state'=>null,'school_badge'=>'JP21'],
            ['english_name'=>'KUMAMOTO UNIVERSITY','chinese_name'=>'熊本大學','country'=>'JAPAN','area'=>null,'state'=>null,'school_badge'=>'JP22'],
            ['english_name'=>'KINDAI UNIVERSITY','chinese_name'=>'近畿大學','country'=>'JAPAN','area'=>null,'state'=>null,'school_badge'=>'JP23'],
            ['english_name'=>'NAGASAKI UNIVERSITY','chinese_name'=>'長崎大學','country'=>'JAPAN','area'=>null,'state'=>null,'school_badge'=>'JP24'],
            ['english_name'=>'OSAKA CITY UNIVERSITY','chinese_name'=>'大阪市立大學','country'=>'JAPAN','area'=>null,'state'=>null,'school_badge'=>'JP25'],
            ['english_name'=>'EHIME UNIVERSITY','chinese_name'=>'愛媛大學','country'=>'JAPAN','area'=>null,'state'=>null,'school_badge'=>'JP26'],
            ['english_name'=>'TOKYO UNIVERSITY OF AGRICULTURE & TECHNOLOGY','chinese_name'=>'東京農工大學','country'=>'JAPAN','area'=>null,'state'=>null,'school_badge'=>'JP27'],
            ['english_name'=>'YOKOHAMA CITY UNIVERSITY','chinese_name'=>'橫濱市立大學','country'=>'JAPAN','area'=>null,'state'=>null,'school_badge'=>'JP28'],
            ['english_name'=>'NIIGATA UNIVERSITY','chinese_name'=>'新潟大學','country'=>'JAPAN','area'=>null,'state'=>null,'school_badge'=>'JP29'],
            ['english_name'=>'JUNTENDO UNIVERSITY','chinese_name'=>'順天堂大學','country'=>'JAPAN','area'=>null,'state'=>null,'school_badge'=>'JP30'],
            ['english_name'=>'Tokyo University of the Arts','chinese_name'=>'東京藝術大學','country'=>'JAPAN','area'=>null,'state'=>null,'school_badge'=>'JP31'],
            ['english_name'=>'Tama Art University','chinese_name'=>'多摩美術大學','country'=>'JAPAN','area'=>null,'state'=>null,'school_badge'=>'JP32'],
            ['english_name'=>'Musashino Art University','chinese_name'=>'武蔵野美術大學','country'=>'JAPAN','area'=>null,'state'=>null,'school_badge'=>'JP33'],
            ['english_name'=>'Tokyo Zokei University','chinese_name'=>'東京造形大學','country'=>'JAPAN','area'=>null,'state'=>null,'school_badge'=>'JP34'],
            ['english_name'=>'Kanazawa College of Art','chinese_name'=>'金澤美術工藝大學','country'=>'JAPAN','area'=>null,'state'=>null,'school_badge'=>'JP35'],
            ['english_name'=>'Aichi Prefectural University of Fine Arts and Music','chinese_name'=>'愛知縣立藝術大學','country'=>'JAPAN','area'=>null,'state'=>null,'school_badge'=>'JP36'],
            ['english_name'=>'Joshibi University of Art and Design','chinese_name'=>'女子美術大學','country'=>'JAPAN','area'=>null,'state'=>null,'school_badge'=>'JP37'],
            ['english_name'=>'Kyoto City University of Arts','chinese_name'=>'京都市立藝術大學','country'=>'JAPAN','area'=>null,'state'=>null,'school_badge'=>'JP38'],
            ['english_name'=>'Kunitachi College of Music','chinese_name'=>'日本國立音樂大學','country'=>'JAPAN','area'=>null,'state'=>null,'school_badge'=>'JP39'],
            ['english_name'=>'Tokyo College of Music','chinese_name'=>'東京音樂大學','country'=>'JAPAN','area'=>null,'state'=>null,'school_badge'=>'JP40'],
            ['english_name'=>'Toho Gakuen School of Music','chinese_name'=>'桐朋學園大學','country'=>'JAPAN','area'=>null,'state'=>null,'school_badge'=>'JP41'],
            ['english_name'=>'Musashino Academia Musicae','chinese_name'=>'武藏野音樂大學','country'=>'JAPAN','area'=>null,'state'=>null,'school_badge'=>'JP42'],
            ['english_name'=>'Okinawa Prefectural University of Arts','chinese_name'=>'沖繩縣立藝術大學','country'=>'JAPAN','area'=>null,'state'=>null,'school_badge'=>'JP43'],
            ['english_name'=>'Tokyo Gakugei University','chinese_name'=>'東京學藝大學','country'=>'JAPAN','area'=>null,'state'=>null,'school_badge'=>'JP44'],
            ['english_name'=>'Tohoku University of Art and Design','chinese_name'=>'東北藝術工科大學','country'=>'JAPAN','area'=>null,'state'=>null,'school_badge'=>'JP45'],
            ['english_name'=>'Seoul National University','chinese_name'=>'首爾國立大學','country'=>'KOREA','area'=>null,'state'=>null,'school_badge'=>'KR1'],
            ['english_name'=>'Pusan National University','chinese_name'=>'釜山國立大學','country'=>'KOREA','area'=>null,'state'=>null,'school_badge'=>'KR2'],
            ['english_name'=>'Kyungpook National University','chinese_name'=>'慶北國立大學','country'=>'KOREA','area'=>null,'state'=>null,'school_badge'=>'KR3'],
            ['english_name'=>'Kangwon National University','chinese_name'=>'江原國立大學','country'=>'KOREA','area'=>null,'state'=>null,'school_badge'=>'KR4'],
            ['english_name'=>'Jeonbuk National University','chinese_name'=>'全北國立大學','country'=>'KOREA','area'=>null,'state'=>null,'school_badge'=>'KR5'],
            ['english_name'=>'Chungbuk national University','chinese_name'=>'忠北國立大學','country'=>'KOREA','area'=>null,'state'=>null,'school_badge'=>'KR6'],
            ['english_name'=>'Chonnam National University','chinese_name'=>'全南國立大學','country'=>'KOREA','area'=>null,'state'=>null,'school_badge'=>'KR7'],
            ['english_name'=>'Chungnam National University','chinese_name'=>'忠南國立大學','country'=>'KOREA','area'=>null,'state'=>null,'school_badge'=>'KR8'],
            ['english_name'=>'Jeju National University','chinese_name'=>'濟州國立大學','country'=>'KOREA','area'=>null,'state'=>null,'school_badge'=>'KR9'],
            ['english_name'=>'Gyeongsang National University','chinese_name'=>'慶尚國立大學','country'=>'KOREA','area'=>null,'state'=>null,'school_badge'=>'KR10'],
            ['english_name'=>'Korea University','chinese_name'=>'高麗大學','country'=>'KOREA','area'=>null,'state'=>null,'school_badge'=>'KR11'],
            ['english_name'=>'Yonsei University','chinese_name'=>'延世大學','country'=>'KOREA','area'=>null,'state'=>null,'school_badge'=>'KR12'],
            ['english_name'=>'Korea Advanced Institute of Science and Technology','chinese_name'=>'韓國科學技術院','country'=>'KOREA','area'=>null,'state'=>null,'school_badge'=>'KR13'],
            ['english_name'=>'Sungkyunkwan University','chinese_name'=>'成均館大學','country'=>'KOREA','area'=>null,'state'=>null,'school_badge'=>'KR14'],
            ['english_name'=>'Pohang University of Science and Technology','chinese_name'=>'浦項科技大學','country'=>'KOREA','area'=>null,'state'=>null,'school_badge'=>'KR15'],
            ['english_name'=>'Hanging University','chinese_name'=>'漢陽大學','country'=>'KOREA','area'=>null,'state'=>null,'school_badge'=>'KR16'],
            ['english_name'=>'Kyunghee University','chinese_name'=>'慶熙大學','country'=>'KOREA','area'=>null,'state'=>null,'school_badge'=>'KR17'],
            ['english_name'=>'Gwangju Institute of Science and Technology','chinese_name'=>'光州科學技術院','country'=>'KOREA','area'=>null,'state'=>null,'school_badge'=>'KR18'],
            ['english_name'=>'Ewha Womans University','chinese_name'=>'梨花女子大學','country'=>'KOREA','area'=>null,'state'=>null,'school_badge'=>'KR19'],
            ['english_name'=>'Sogang University','chinese_name'=>'西江大學','country'=>'KOREA','area'=>null,'state'=>null,'school_badge'=>'KR20'],
            ['english_name'=>'Chungang University','chinese_name'=>'中央大學','country'=>'KOREA','area'=>null,'state'=>null,'school_badge'=>'KR21'],
            ['english_name'=>'Hankuk University of Foreign Studies','chinese_name'=>'韓國外國語大學','country'=>'KOREA','area'=>null,'state'=>null,'school_badge'=>'KR22'],
            ['english_name'=>'University of Seoul','chinese_name'=>'首爾市立大學','country'=>'KOREA','area'=>null,'state'=>null,'school_badge'=>'KR23'],
            ['english_name'=>'Ulsan National Institute of Science and Technology','chinese_name'=>'蔚山科學技術大學','country'=>'KOREA','area'=>null,'state'=>null,'school_badge'=>'KR24'],
            ['english_name'=>'Sejong University','chinese_name'=>'世宗大學','country'=>'KOREA','area'=>null,'state'=>null,'school_badge'=>'KR25'],
            ['english_name'=>'National University of Singapore','chinese_name'=>'新加坡國立大學','country'=>'SINGAPORE','area'=>null,'state'=>null,'school_badge'=>'SG1'],
            ['english_name'=>'Nanyang Technological University','chinese_name'=>'南洋理工大學','country'=>'SINGAPORE','area'=>null,'state'=>null,'school_badge'=>'SG2'],
            ['english_name'=>'Singapore Management University','chinese_name'=>'新加坡管理大學','country'=>'SINGAPORE','area'=>null,'state'=>null,'school_badge'=>'SG3'],
            ['english_name'=>'Singapore University of Technology and Design','chinese_name'=>'新加坡科技設計大學','country'=>'SINGAPORE','area'=>null,'state'=>null,'school_badge'=>'SG4'],
            ['english_name'=>'Singapore Institute of Technology','chinese_name'=>'新加坡理工大學','country'=>'SINGAPORE','area'=>null,'state'=>null,'school_badge'=>'SG5'],
            ['english_name'=>'Singapore University of Social Sciences','chinese_name'=>'新躍社科大學','country'=>'SINGAPORE','area'=>null,'state'=>null,'school_badge'=>'SG6'],
            ['english_name'=>'University of the Arts Singapore','chinese_name'=>'新加坡藝術大學','country'=>'SINGAPORE','area'=>null,'state'=>null,'school_badge'=>'SG7'],
            ['english_name'=>'The University of Hong Kong','chinese_name'=>'香港大學','country'=>'HONG KONG','area'=>null,'state'=>null,'school_badge'=>'HK1'],
            ['english_name'=>'The Chinese University of Hong Kong','chinese_name'=>'香港中文大學','country'=>'HONG KONG','area'=>null,'state'=>null,'school_badge'=>'HK2'],
            ['english_name'=>'The Hong Kong University of Science and Technology','chinese_name'=>'香港科技大學','country'=>'HONG KONG','area'=>null,'state'=>null,'school_badge'=>'HK3'],
            ['english_name'=>'The Hong Kong Polytechnic University','chinese_name'=>'香港理工大學','country'=>'HONG KONG','area'=>null,'state'=>null,'school_badge'=>'HK4'],
            ['english_name'=>'Hong Kong Baptist University','chinese_name'=>'香港浸會大學','country'=>'HONG KONG','area'=>null,'state'=>null,'school_badge'=>'HK5'],
            ['english_name'=>'City University of Hong Kong','chinese_name'=>'香港城市大學','country'=>'HONG KONG','area'=>null,'state'=>null,'school_badge'=>'HK6'],
            ['english_name'=>'Lingnan University','chinese_name'=>'嶺南大學','country'=>'HONG KONG','area'=>null,'state'=>null,'school_badge'=>'HK7'],
            ['english_name'=>'The Education University of Hong Kong','chinese_name'=>'香港教育大學','country'=>'HONG KONG','area'=>null,'state'=>null,'school_badge'=>'HK8'],
            ['english_name'=>'Hong Kong Metropolitan University','chinese_name'=>'香港都會大學','country'=>'HONG KONG','area'=>null,'state'=>null,'school_badge'=>'HK9'],
            ['english_name'=>'Hong Kong Shue Yan University','chinese_name'=>'香港樹仁大學','country'=>'HONG KONG','area'=>null,'state'=>null,'school_badge'=>'HK10'],
            ['english_name'=>'Hang Seng University of Hong Kong ','chinese_name'=>'香港恒生大學','country'=>'HONG KONG','area'=>null,'state'=>null,'school_badge'=>'HK11'],
            ['english_name'=>'Universidade de Macau','chinese_name'=>'澳門大學','country'=>'MACAU','area'=>null,'state'=>null,'school_badge'=>'MO1'],
            ['english_name'=>'Universidade Politécnica de Macau','chinese_name'=>'澳門理工大學','country'=>'MACAU','area'=>null,'state'=>null,'school_badge'=>'MO2'],
            ['english_name'=>'Instituto de Formação Turística de Macau','chinese_name'=>'澳門旅遊學院','country'=>'MACAU','area'=>null,'state'=>null,'school_badge'=>'MO3'],
            ['english_name'=>'Universidade de Ciência e Tecnologia de Macau','chinese_name'=>'澳門科技大學','country'=>'MACAU','area'=>null,'state'=>null,'school_badge'=>'MO4'],
            ['english_name'=>'Universidade da Cidade de Macau','chinese_name'=>'澳門城市大學','country'=>'MACAU','area'=>null,'state'=>null,'school_badge'=>'MO5'],
            ['english_name'=>'Universidade de São José','chinese_name'=>'聖若瑟大學','country'=>'MACAU','area'=>null,'state'=>null,'school_badge'=>'MO6'],
            ['english_name'=>'Instituto de Enfermagem Kiang Wu de Macau','chinese_name'=>'澳門鏡湖護理學院','country'=>'MACAU','area'=>null,'state'=>null,'school_badge'=>'MO7'],
            ['english_name'=>'Instituto de Gestão de Macau','chinese_name'=>'澳門管理學院','country'=>'MACAU','area'=>null,'state'=>null,'school_badge'=>'MO8'],
            ['english_name'=>'Instituto Milénio de Macau','chinese_name'=>'中西創新學院','country'=>'MACAU','area'=>null,'state'=>null,'school_badge'=>'MO9'],
            ['english_name'=>'Taipei American School','chinese_name'=>'臺北美國學校','country'=>'TAIWAN','area'=>null,'state'=>null,'school_badge'=>'TWIS1'],
            ['english_name'=>'Grace Christian Academy','chinese_name'=>'恩慈美國學校','country'=>'TAIWAN','area'=>null,'state'=>null,'school_badge'=>'TWIS2'],
            ['english_name'=>'Dominican International School','chinese_name'=>'臺北市私立道明外僑學校','country'=>'TAIWAN','area'=>null,'state'=>null,'school_badge'=>'TWIS3'],
            ['english_name'=>'MorrisonAcademy-Taipei Bethany American School','chinese_name'=>'臺北伯大尼美國學校','country'=>'TAIWAN','area'=>null,'state'=>null,'school_badge'=>'TWIS4'],
            ['english_name'=>'Taipei Adventist American School','chinese_name'=>'臺北復臨美國學校','country'=>'TAIWAN','area'=>null,'state'=>null,'school_badge'=>'TWIS5'],
            ['english_name'=>'Taipei European School','chinese_name'=>'臺北歐洲學校','country'=>'TAIWAN','area'=>null,'state'=>null,'school_badge'=>'TWIS6'],
            ['english_name'=>'Taipei Japanese School','chinese_name'=>'臺北市日僑學校','country'=>'TAIWAN','area'=>null,'state'=>null,'school_badge'=>'TWIS7'],
            ['english_name'=>'Taipei Korean School','chinese_name'=>'臺北韓國學校','country'=>'TAIWAN','area'=>null,'state'=>null,'school_badge'=>'TWIS8'],
            ['english_name'=>'New Taipei City Asia American International Academy','chinese_name'=>'新北市華美國際美國學校','country'=>'TAIWAN','area'=>null,'state'=>null,'school_badge'=>'TWIS9'],
            ['english_name'=>'Taoyuan American School','chinese_name'=>'桃園美國學校','country'=>'TAIWAN','area'=>null,'state'=>null,'school_badge'=>'TWIS10'],
            ['english_name'=>'Hsinchu American School','chinese_name'=>'新竹美國學校','country'=>'TAIWAN','area'=>null,'state'=>null,'school_badge'=>'TWIS11'],
            ['english_name'=>'Hsinchu International School','chinese_name'=>'新竹荷蘭國際學校','country'=>'TAIWAN','area'=>null,'state'=>null,'school_badge'=>'TWIS12'],
            ['english_name'=>'Pacific American School','chinese_name'=>'亞太美國學校','country'=>'TAIWAN','area'=>null,'state'=>null,'school_badge'=>'TWIS13'],
            ['english_name'=>'American School in Taichung','chinese_name'=>'臺中美國學校','country'=>'TAIWAN','area'=>null,'state'=>null,'school_badge'=>'TWIS14'],
            ['english_name'=>'Morrison Academy Taichung','chinese_name'=>'臺中馬禮遜美國學校','country'=>'TAIWAN','area'=>null,'state'=>null,'school_badge'=>'TWIS15'],
            ['english_name'=>'Taichung Japanese School','chinese_name'=>'臺中市日僑學校','country'=>'TAIWAN','area'=>null,'state'=>null,'school_badge'=>'TWIS16'],
            ['english_name'=>'Kaohsiung American School','chinese_name'=>'高雄美國學校','country'=>'TAIWAN','area'=>null,'state'=>null,'school_badge'=>'TWIS17'],
            ['english_name'=>'Dominican International School Kaohsiung','chinese_name'=>'高雄市道明外僑學校','country'=>'TAIWAN','area'=>null,'state'=>null,'school_badge'=>'TWIS18'],
            ['english_name'=>'Kaohsiung Japanese School','chinese_name'=>'高雄市日僑學校','country'=>'TAIWAN','area'=>null,'state'=>null,'school_badge'=>'TWIS19'],
            ['english_name'=>'Kaohsiung Korean School','chinese_name'=>'高雄韓國學校','country'=>'TAIWAN','area'=>null,'state'=>null,'school_badge'=>'TWIS20'],
            ['english_name'=>'Morrison Academy Kaohsiung','chinese_name'=>'高雄馬禮遜美國學校','country'=>'TAIWAN','area'=>null,'state'=>null,'school_badge'=>'TWIS21'],
            ['english_name'=>'Kang Chiao International School Xiugang Campus','chinese_name'=>'康橋國際學校秀岡校區','country'=>'TAIWAN','area'=>null,'state'=>null,'school_badge'=>'TWIS22'],
            ['english_name'=>'Kang Chiao International School (Linkou Campus)','chinese_name'=>'康橋國際學校林口校區','country'=>'TAIWAN','area'=>null,'state'=>null,'school_badge'=>'TWIS23'],
            ['english_name'=>'Kang Chiao International School (Hsinchu Campus)','chinese_name'=>'康橋國際學校新竹校區','country'=>'TAIWAN','area'=>null,'state'=>null,'school_badge'=>'TWIS24'],
            ['english_name'=>'Taipei Kuei Shan School','chinese_name'=>'台北奎山中學','country'=>'TAIWAN','area'=>null,'state'=>null,'school_badge'=>'TWIS25'],
            ['english_name'=>'Taoyuan Municipal Dayuan International Senior High School','chinese_name'=>'桃園市立大園國際高級中等學校','country'=>'TAIWAN','area'=>null,'state'=>null,'school_badge'=>'TWIS26'],
            ['english_name'=>'Taipei Fuhsing Private School','chinese_name'=>'復興實驗高級中學','country'=>'TAIWAN','area'=>null,'state'=>null,'school_badge'=>'TWIS27'],
            ['english_name'=>'Mingdao High School','chinese_name'=>'台中明道國際學校','country'=>'TAIWAN','area'=>null,'state'=>null,'school_badge'=>'TWIS28'],
            ['english_name'=>'Victoria Academy','chinese_name'=>'雲林維多利亞學院','country'=>'TAIWAN','area'=>null,'state'=>null,'school_badge'=>'TWIS29'],
            ['english_name'=>'Taipei Wego Bilingual Senior High School','chinese_name'=>'薇閣雙語高級中學','country'=>'TAIWAN','area'=>null,'state'=>null,'school_badge'=>'TWIS30'],
            ['english_name'=>'I-Shou International School','chinese_name'=>'義大國際高級中學','country'=>'TAIWAN','area'=>null,'state'=>null,'school_badge'=>'TWIS31'],
            ['english_name'=>'Morrison Academy Taipe','chinese_name'=>'台北馬禮遜美國學校','country'=>'TAIWAN','area'=>null,'state'=>null,'school_badge'=>'TWIS32'],
        ];

//        \App\University::insert($universities);
        foreach($universities as $university){
            \App\University::create([
                'slug' => str_slug($university['english_name']),
                'name' => $university['chinese_name'],
                'english_name' => $university['english_name'],
                'chinese_name' => $university['chinese_name'],
                'country' => $university['country'],
                'area' => $university['area'],
                'state' => $university['state'],
                'school_badge' => $university['school_badge'],
                'image_path' => 'university/'.$university['country'].'/'.$university['school_badge'].'.png'
            ]);
        }
    }
}
