version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    container_name: yizixue_app
    volumes:
      - .:/var/www
    depends_on:
      - db

  nginx:
    image: nginx:stable
    container_name: yizixue_nginx
    ports:
      - "8088:80"
    volumes:
      - .:/var/www
      - ./docker/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  db:
    image: mariadb:10.5
    container_name: yizixue_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: yizixue
      MYSQL_USER: yizixue
      MYSQL_PASSWORD: secret
    ports:
      - "33066:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
